### ISSUE TITLE
Add instructions for the community to contribute to Velero helm chart in the new repository

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/helm-charts#1]
From @cpanato:
> Include disclaimer README similar to https://github.com/elastic/helm-charts#elastic-stack-kubernetes-helm-chart. Also note these charts are community maintained, and add a basic statement about how to get involved (because it will be your own GitHub repo, you no longer need to rely on the helm/charts OWNERS file, but can add collaborators directly to the repo, if per-chart access is desired use GitHub native CODEOWNERS, etc). This all helps keep the burden low for the Velero team, and shows support for Velero Helm Charts without adding additional liability

I am assuming this will be on a per chart/project basis.

**Comment by carlisia** [comment]
Also from @cpanato:
> Would you want to invite the current maintainers of these charts to the new GitHub repo, per item 3 above? Currently listed owners:
stable/velero OWNERS: @hectorj2f @nrb @prydonius (the last two are already vmware members 😄 )

The answer to that is yes.

**Comment by nrb** [comment]
@carlisia Could you invite all of the members of @vmware-tanzu/velero-owners ?

**Comment by carlisia** [comment]
Done.

**Comment by cpanato** [comment]
can invite me if you want 😇 lol

**Comment by carlisia** [comment]
That's a great idea! Let me just check with the others.

**Comment by carlisia** [comment]
I am closing this, we can reopen if/when someone wants to add this documentation.
