### ISSUE TITLE
Velero -> Helm 3 -> Error: backupstoragelocation.velero.io "default" not found

### ISSUE THREAD

**Issue by tmarinov** [vmware-tanzu/helm-charts#101]
Velero version:
> velero version
Client:  Version: v1.3.2; Git commit: -;
Server: Version: v1.3.1

Velero Helm chart:
> Name: vmware-tanzu/velero;
 Chart version:2.9.13;
 App version: 1.3.1;

Helm version:
> helm version
version.BuildInfo{Version:"v3.1.1", GitCommit:"afe70585407b420d0097d07b21c47dc511525ac8", GitTreeState:"clean", GoVersion:"go1.13.8"}

Trying to install Velero by using Helm 3, but having the following issues:
1. Info (error?) during the installation:

> helm install vmware-tanzu/velero --namespace velero   -f values.yaml --generate-name
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
NAME: velero-1587110000
LAST DEPLOYED: Fri Apr 17 09:53:25 2020
NAMESPACE: velero
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Check that the velero is up and running:

    kubectl get deployment/velero-1587110000 -n velero

> Check that the secret has been created:

    kubectl get secret/velero-1587110000 -n velero

The deployment is running (no errors in the pod logs):

> kubectl get deployment/velero-1587110000 -n velero
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
velero-1587110000   1/1     1            1           7h

Secrets (cannot find a secret with exact match of the name above):
> kubectl get secrets --namespace velero
NAME                                      TYPE                                  DATA   AGE
cloud-credentials                         Opaque                                1      7h10m
default-token-jssb6                       kubernetes.io/service-account-token   3      7h11m
sh.helm.release.v1.velero-1587110000.v1   helm.sh/release.v1                    1      7h5m
velero-1587110000-server-token-gmvmx      kubernetes.io/service-account-token   3      7h5m
velero-restic-credentials                 Opaque              

2. Error when try to create a backup:
> Validation errors:  a BackupStorageLocation CRD with the name specified in the backup spec needs to be created before this backup can be executed. Error: backupstoragelocation.velero.io "default" not found

Please, advice what is wrong with the above installation

**Comment by jblackburn21** [comment]
I just ran into this, make sure your --storage-location and --volume-snapshot-locations flags match what you set for configuration.backupStorageLocation.name and configuration.volumeSnapshotLocation.name.

You can also set these names to "default" so that you don't have to provide the flags.

**Comment by tmarinov** [comment]
Thanks @jblackburn21 ,
This solved the problem and now it's  working!
