### ISSUE TITLE
Helm install documentation has no info about how to specify the --set-file key

### ISSUE THREAD

**Issue by cprivite** [vmware-tanzu/helm-charts#103]
When you run helm install with the --set-file argument, you need to provide a key to which the file you're passing in is mapped to. Unfortunately, the current helm-charts/charts/velero/README.md  doesn't give you any clues about what that should be. 

This was handed in the past via the main velero documentation by the docs created in this issue: https://github.com/vmware-tanzu/velero/issues/1533 

Unfortunately, the documentation has been revised since version 1.1.0 and that page doesn't exist anymore. Thus we've lost the only clue about how to properly format the --set-file argument and now the currently provided helm install block in the readme isn't valid or helpful.

The AWS plugin documentation is not helpful at all as it ignores the helm use case entirely.

I've only figured out how to fix this for the AWS plugin, so I can't really suggest a generic solution for the document, but I do know that for a new user doing a new install right now, this was a major blockage in being able to use the helm install of Velero whatsoever.

For passing in AWS credentials file that most walkthroughs have you create, here's what you want:

`--set-file credentials.secretContents.cloud=./credentials-velero`

If nothing else, hopefully this issue will save someone else hours of debugging.

**Comment by optimus-kart** [comment]
What should be the key for azure credentials?
I am surprised no one has looked it till now

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
I am struggling with this problem trying to deploy with the Helm Chart using Azure blog storage. The error I get in the deployed (crashed) container is below.

```
An error occurred: some backup storage locations are invalid: error getting backup store for location "azure": rpc error: code = Unknown desc = error loading environment from AZURE_CREDENTIALS_FILE (/credentials/cloud): open /credentials/cloud: no such file or directory
```

I would like to use a Kubernetes secret instead of feeding a file to Helm, but it looks to me like the chart does not create this /credentials/cloud file that the Go code is looking for. I have `existingSecret` set to true.

**Comment by f35f0ef9d0e827dae86552d3899f78fc** [comment]
OK, I was able to finally get past my problem by reading issue #21 
This command helped me create the secret properly. Notice the **cloud** portion.
`kubectl -n dev create secret generic mysecret --from-file=cloud=azure-storage-creds`

Contents of azure-storage-creds:
AZURE_STORAGE_ACCOUNT_ACCESS_KEY=
AZURE_CLOUD_NAME=AzurePublicCloud

I retrieved the storage account access key using the command in the plugin [readme](https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure#option-3-use-storage-account-access-key), however I had to add the `--subscription` parameter to it.

**Comment by cprivite** [comment]
I'm concerned no one who manages velero has assigned/rejected/commented on this yet. Velero is still a supported product right? One would hope the issues are actively reviewed at least as much as the open source projects that VMWare contributes to...

**Comment by carlisia** [comment]
I'll be looking at this tomorrow.

**Comment by carlisia** [comment]
@optimus-kart 

> What should be the key for azure credentials?

The key is the same for any provider.
