### ISSUE TITLE
Implement custom CA for BackupStorageLocation

### ISSUE THREAD

**Issue by vmwiz** [vmware-tanzu/helm-charts#121]
Following https://github.com/vmware-tanzu/velero/issues/1027 / https://github.com/vmware-tanzu/velero/issues/2330 / https://github.com/vmware-tanzu/velero/issues/2332 / https://github.com/vmware-tanzu/velero/issues/2333

Please adapt the Helm chart to allow setting a custom CA bundle in the BackupStorageLocation

**Comment by reddiablo85** [comment]
linking: https://github.com/vmware-tanzu/velero/issues/2675

**Comment by carlisia** [comment]
Fixed here: https://github.com/vmware-tanzu/helm-charts/pull/128

Thanks for bringing this up @vmwiz!
