### ISSUE TITLE
Support --default-volumes-to-restic flag in values.yaml

### ISSUE THREAD

**Issue by acanewby** [vmware-tanzu/helm-charts#122]
[Additional settings](https://velero.io/docs/master/customize-installation/#enable-restic-integration) are required when installing velero directly via command line.

Specifically, you need to pass the following:

- `--use-restic` to cause `restic` support to be installed
- `--default-volumes-to-restic` if you want all volumes to be backed up by `restic` by default

If you do not specify the second flag, you have to add the `backup.velero.io/backup-volumes` annotation to each pod that uses a volume you want to back up.

As far as I can tell, the current helm chart supports the first flag if you specify `deployRestic: true` in the `values.yaml`.  However, I can't see how/if there is any support in the chart for the `--default-volumes-to-restic` option.

Without this, you have to go through the tedious process of manually annotating every pod that consumes a PV you want backed up.

Am I misunderstanding the chart?  If so, please let me know how to implement the above.

**Comment by tlvenn** [comment]
There is definitely something missing so that restic integration can be configured to include all your volumes (opt-out strategy) by default, however you can still do it by passing the flag when you create the backup:
>`velero backup create BACKUP_NAME --default-volumes-to-restic OTHER_OPTIONS`
