### ISSUE TITLE
Verify lint failure

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/helm-charts#13]
Adding this as a reminder to check the lint failures. I merged the PR below before waiting for the check results:

https://github.com/vmware-tanzu/helm-charts/runs/355089737

**Comment by carlisia** [comment]
c/c @cpanato

**Comment by cpanato** [comment]
this looks like a Github issue, this is part of the Github, maybe at that time try to re-run the check.
let observer if that happens again but for now no action from my side

@carlisia

**Comment by carlisia** [comment]
Closing, not an issue. Lint tests are passing: https://github.com/vmware-tanzu/helm-charts/runs/358213218
