### ISSUE TITLE
Prometheus Operator CRDs

### ISSUE THREAD

**Issue by mdarii** [vmware-tanzu/helm-charts#134]
I see in commit: https://github.com/vmware-tanzu/helm-charts/commit/ed282ba70c2b63ce0e44e2ecd23ad3c175762a4c#diff-59c039e2299056296b9ae746b2d2b39c was removed support for prometheus operator servicemonitor, what was reason for that change, this is a very useful feature, do you plan to add it back?

**Comment by carlisia** [comment]
Hi @mdarii, yes the removal was intentional, you will find the reasoning here: https://github.com/vmware-tanzu/velero/issues/2221.

Being that Prometheus has its own Helm chart, that is what should be used instead. I will close this issue.

**Comment by carlisia** [comment]
Hey @mdarii, we reverted the removal.
