### ISSUE TITLE
CRDs aren't generated when using standalone Helm (2/3)

### ISSUE THREAD

**Issue by tom-hadlaw-hs** [vmware-tanzu/helm-charts#143]
**What steps did you take and what happened:**

Generating the manifests locally using helm 3 (v3.2.4):

`helm template vmware-tanzu/velero`

**What did you expect to happen:**

Helm to output all manifests, including CustomResourceDefinitions.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

Looks like the charts where recently changed to only generate CRDs when using Tiller: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/crds.yaml#L1

**Environment:**

- helm version (use `helm version`):  v3.2.4
- helm chart version and app version:
  - helm2 (use `helm list`):
  - helm3 (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): Darwin

**Comment by jenting** [comment]
Please run `helm template vmware-tanzu/velero --include-crds` on helm3, thanks.

**Comment by jenting** [comment]
Consider it as close, feel free to re-open it.
