### ISSUE TITLE
[velero] Upgrade to Velero v1.5

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/helm-charts#147]
There are new CRDs and at least one new flag.

Please see: https://github.com/vmware-tanzu/velero/issues/2717.

**Comment by jenting** [comment]
I've proposed #146 so the CRDs are no needed to be manually update anymore from now and in the future.

**Comment by bclermont** [comment]
1.5.1 had been release

**Comment by svcua** [comment]
https://github.com/vmware-tanzu/helm-charts/pull/163

**Comment by jaygorrell** [comment]
Any chance of getting a Helm release? 1.5 is needed for EKS IAM integration because it includes the aws-sdk version bump.

**Comment by jenting** [comment]
helm chart `2.13.0` release https://github.com/vmware-tanzu/helm-charts/releases/tag/velero-2.13.0 :rocket: 
Thanks to @svcua and all :tada:
