### ISSUE TITLE
Enable DCO checker

### ISSUE THREAD

**Issue by cpanato** [vmware-tanzu/helm-charts#15]
Per this doc https://github.com/vmware-tanzu/helm-charts/blob/master/CONTRIBUTING.md#dco-sign-off contributors need to sign off the commits

so to make sure this is done will be good to enable the https://github.com/probot/dco or any other solution that vmware have.

cc @carlisia

**Comment by carlisia** [comment]
Good point! I'll take this on.

**Comment by carlisia** [comment]
I made a request, think @timh needs to approve it.

**Comment by carlisia** [comment]
Done!

![image](https://user-images.githubusercontent.com/16508/72009981-d5219b80-320b-11ea-8def-0af63e915543.png)
