### ISSUE TITLE
"default" backup storage location not created with Helm chart 2.12.17

### ISSUE THREAD

**Issue by vitobotta** [vmware-tanzu/helm-charts#164]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Hi! I have been using Velero for a while without any problems, and I use Pulumi to install and upgrade it using the Helm chart.
I am trying to upgrade to to v1.5.1 with the chart 2.12.17 and everything works fine apart from the fact that the backup storage location is not created with this version.

Here are my settings:

```
          configuration: {
            provider: "aws",
            backupStorageLocation: {
              provider: "aws",
              name: "default",
              bucket: ...,
              config: {
                region: ...,
                s3Url: ...
              },
              prefix: ...
            },
          },
```

I am using the same settings I have been using for months and it doesn't seem like the structure of values.yaml has changed, so I don't understand why it doesn't create the backup storage location.

**What did you expect to happen:**
The backup storage location to be created as per the settings in the values.yaml (mapped in Pulumi in my case but it's the same thing).

**Environment:**

- helm version (use `helm version`): 
3.3.3
- helm chart version and app version:
2.12.17
- Kubernetes version (use `kubectl version`):
v1.18.6
- Kubernetes installer & version:
Rancher 2.4.7
- Cloud provider or hardware configuration:
Hetzner Cloud (VMs)
- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04

**Comment by jenting** [comment]
@vitobotta sorry for the late reply, could you please provide the previous helm chart version? thanks.

**Comment by vitobotta** [comment]
@jenting Hi, I can't remember - in the meantime I installed with the CLI binary instead of the helm chart.

**Comment by jenting** [comment]
> @jenting Hi, I can't remember - in the meantime I installed with the CLI binary instead of the helm chart.

close it, feel free to reopen once we have more information on this.
