### ISSUE TITLE
[bug] First install CRD's, then install resources that depends on CRD's

### ISSUE THREAD

**Issue by MaxymVlasov** [vmware-tanzu/helm-charts#167]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

1. Try to up Velero in new cluster using [this `values.yaml`](https://github.com/MaxymVlasov/helm-charts-1/blob/8a653ce4750d0ca7b579467f301192c04b48b17d/charts/velero/examples/vsphere/values.yaml) from #166 
2. Run `helmfile -f helmfile.yaml diff` and `helmfile -f helmfile.yaml apply`.
3. Get same error `... no matches for kind "Schedule" in version "velero.io/v1"` - it means that CRD resources not yet exist.

**What did you expect to happen:**
Schedules should be created after created CRD resources. At least `apply` should be done without errors

**The output of the following commands will help us better understand what's going on**:
https://pastebin.com/EeZ2KPWX

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
Could be related to: #44 

**Environment:**

- helm version (use `helm version`): v3.3.1"
- helm chart version and app version: 
  - Chart: 2.12.17
  - app: v1.4.2
- Kubernetes version (use `kubectl version`): v1.17.2
- Kubernetes installer & version: Rancher v2.3.5
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04.3 LTS

**Comment by jenting** [comment]
@MaxymVlasov please check #153 thanks.
