### ISSUE TITLE
Add option in values.yaml to customize secret name

### ISSUE THREAD

**Issue by csgtree** [vmware-tanzu/helm-charts#181]
**Describe the problem/challenge you have**
If we install velero server via helm chart instead of velero cli, the secret name is `{{ include "velero.fullname" . }}`.
However, the vSphere plugin requires the secret with name `cloud-credentials`. Or the vSphere plugin installation will fail.

**Describe the solution you'd like**
Add option in values.yaml to configure secret name separately.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 
v3.1.2
- helm chart version and app version:
  - helm2 (use `helm list`):
  - helm3 (use `helm list -n <YOUR NAMESPACE>`): velero-2.12.17
- Kubernetes version (use `kubectl version`): v1.16.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by jenting** [comment]
@csgtree good finding, would you mind create a PR for this? thanks.
