### ISSUE TITLE
velero helm install does not use user provided service account

### ISSUE THREAD

**Issue by martin2176** [vmware-tanzu/helm-charts#182]
What I intend to achieve:
I want velero to use the service account I precreated before the install. And the reason being I want to be able to assign a custom role to the service account (not cluster admin) .
kubectl --context=martin-aks1-admin -n ecom get sa
NAME        SECRETS   AGE
default     1         17m
velero-sa   1         56s
 I have given velero-sa the appropriate role via role binding

Here is the helm I am running. The deployment does not use the "velero-sa" service account. 

helm install velero vmware-tanzu/velero --dry-run  \
--kube-context $KUBE_CONTEXT --namespace $NAMESPACE  \
--set image.repository=velero/velero \
--set image.tag=v1.5.1 \
--set image.pullPolicy=IfNotPresent \
--set resources.limits.cpu=200m \
--set resources.limits.memory=512Mi \
--set resources.requests.cpu=100m \
--set resources.requests.memory=256Mi \
--set initContainers[0].name=velero-plugin-for-microsoft-azure \
--set initContainers[0].image=velero/velero-plugin-for-microsoft-azure:v1.1.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins \
--set metrics.enabled=false \
--set installCRDs=true \
--set configuration.provider=azure \
--set configuration.backupStorageLocation.name=default \
--set configuration.backupStorageLocation.bucket=$BLOB_CONTAINER \
--set configuration.backupStorageLocation.config.resourceGroup=$AZURE_BACKUP_RESOURCE_GROUP \
--set configuration.backupStorageLocation.config.subscriptionId=$AZURE_BACKUP_SUBSCRIPTION_ID \
--set configuration.backupStorageLocation.config.storageAccount=$AZURE_STORAGE_ACCOUNT_ID \
--set configuration.backupStorageLocation.config.storageAccountKeyEnvVar='AZURE_STORAGE_ACCOUNT_ACCESS_KEY' \
--set backupSyncPeriod=5m \
--set logLevel=error \
--set logFormat=text \
--set rbac.create=false \
--set rbac.clusterAdministrator=false \
--set serviceAccount.server.create=false \
--set serviceAccount.name=velero-sa \
--set-file credentials.secretContents.cloud=/scratch/velero/credentials-velero-aks1 \
--set backupsEnabled=true \
--set snapshotsEnabled=false \
--set deployRestic=false

----here is the deployment from dry run. as you can see its using default service account---
--- I have copied only the relevant section---

# Source: velero/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  labels:
    app.kubernetes.io/name: velero
    app.kubernetes.io/instance: velero
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: velero-2.13.6
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: velero
      app.kubernetes.io/name: velero
  template:
    metadata:
      labels:
        name: velero
        app.kubernetes.io/name: velero
        app.kubernetes.io/instance: velero
        app.kubernetes.io/managed-by: Helm
        helm.sh/chart: velero-2.13.6
    spec:
      restartPolicy: Always
      **serviceAccountName: default**
      containers:
        - name: velero
          image: "velero/velero:v1.5.1"

**Comment by jenting** [comment]
@martin2176 
Please update your input parameter from
```
--set serviceAccount.name=velero-sa
```
to
```
--set serviceAccount.server.name=velero-sa
```

**Comment by jenting** [comment]
I'm going to close it since I could verify the value of `serviceAccountName` is correct when I use `helm template` and the inputs you provided.
