### ISSUE TITLE
Velero installation failing with Error: unknown field "dnsPolicy" in io.k8s.api.core.v1.Container

### ISSUE THREAD

**Issue by sagar-jadhav** [vmware-tanzu/helm-charts#189]
**What steps did you take and what happened:**

1. Install Velero 

```
helm install vmware-tanzu/velero --namespace <YOUR NAMESPACE> \
--set-file credentials.secretContents.cloud=<FULL PATH TO FILE> \
--set configuration.provider=<PROVIDER NAME> \
--set configuration.backupStorageLocation.name=<BACKUP STORAGE LOCATION NAME> \
--set configuration.backupStorageLocation.bucket=<BUCKET NAME> \
--set configuration.backupStorageLocation.config.region=<REGION> \
--set configuration.volumeSnapshotLocation.name=<VOLUME SNAPSHOT LOCATION NAME> \
--set configuration.volumeSnapshotLocation.config.region=<REGION> \
--set image.repository=velero/velero \
--set image.tag=v1.5.1 \
--set image.pullPolicy=IfNotPresent \
--set initContainers[0].name=velero-plugin-for-aws \
--set initContainers[0].image=velero/velero-plugin-for-aws:v1.1.0 \
--set initContainers[0].volumeMounts[0].mountPath=/target \
--set initContainers[0].volumeMounts[0].name=plugins \
--generate-name
```
The above command exited with an error.

**What did you expect to happen:**
Velero should install successfully using Helm Chart

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

```
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(DaemonSet.spec.template.spec.containers[0]): unknown field "dnsPolicy" in io.k8s.api.core.v1.Container
```

**Anything else you would like to add:**
- [PR](https://github.com/vmware-tanzu/helm-charts/pull/188/files) is causing the issue.
- We should use some kind of flag for e.g. `useDNSPolicy=false` for backward compatibility
- As a workaround using the `--version 2.13.9` option in the helm install command is solving the issue.

**Environment:**

- helm version (use `helm version`): v3.2.1+gfe51cd1
- helm chart version and app version:
  - helm2 (use `helm list`):
  - helm3 (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`): v1.16.2+853223d
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by damoon** [comment]
this happens because the dnsPolicy was added on the wrong indentation.
it needs to be in pod level on on container level.

**Comment by sagar-jadhav** [comment]
Thank you @damoon , @jenting
