### ISSUE TITLE
Migrate open Velero chart PRs from the stable/charts repo to this one

### ISSUE THREAD

**Issue by nrb** [vmware-tanzu/helm-charts#19]
~https://github.com/helm/charts/pull/16783 => https://github.com/vmware-tanzu/helm-charts/pull/21~
https://github.com/helm/charts/pull/18472
~https://github.com/helm/charts/pull/17585 => #22~

These 3 PRs are all pending my reviews, and now that the chart in that repo is deprecated, I'd like to get them moved over here.

I can help do that, probably 1 PR at a time.

**Comment by nrb** [comment]
Ok, one more left. That one may take a little longer, as I have a pending review that I didn't finish. I remember starting it one evening during KubeCon, but I think it may have actually been fixed by another, already accepted PR so I need to do some research.

**Comment by carlisia** [comment]
I opened an issue to track the left over one: https://github.com/vmware-tanzu/helm-charts/issues/129

Closing this.
