### ISSUE TITLE
Get Prometheus-operator's servicemonitor back

### ISSUE THREAD

**Issue by machine424** [vmware-tanzu/helm-charts#195]
Hello,

The support of Prometheus-operator's servicemonitor support was dropped [here](https://github.com/vmware-tanzu/helm-charts/commit/ed282ba70c2b63ce0e44e2ecd23ad3c175762a4c) and [here](https://github.com/vmware-tanzu/helm-charts/commit/a9f8d6112185e2921fb1658b84c0f61f3c9aa17a), 

I would like to know if it is possible to get servicemonitor back, or at least [podmonitor](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#podmonitor) if you don't want to add a service.

We've already tried to do so [here](https://github.com/vmware-tanzu/helm-charts/issues/134) in vain, I think there is a misunderstanding: We don't ask this chart to manage Prometheus-operator's CRDs, we only want this chart to instantiate some of the objects that are defined in those CRDs, see [here](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-custom-objects) for the difference.

Prometheus-operator is widely used to deploy the Prometheus stack, and when its APIs change, [backward compatibility is ensured](https://github.com/prometheus-operator/prometheus-operator#prometheus-operator), so adding servicemonitor will not require a lot of maintenance (you can count on the community if you're not familiar with Prometheus-operator/Prometheus).

Plus, servicemonitor resource is widely supported by other charts, see [here](https://github.com/helm/charts/search?q=servicemonitor), and adding it to the chart will avoid manually deploying/managing it outside of the velero release.

What do you think?

**Comment by carlisia** [comment]
I think we've heard this request enough that we should consider it. @jenting would you be onboard with putting this back?

**Comment by carlisia** [comment]
@machine424 we reverted the removal.

**Comment by machine424** [comment]
@carlisia, great, thanks  for your comprehension.

just one last point: It seems more logical to me to have `scrapeInterval` under the stanza `metrics.serviceMonitor` as it sets a field of the servicemonitor.

I can create a PR for that, but I think (I assume the chart complies to semver like velero does) we'll need to ensure backward compatibility or keep that for the next major version bump.

**Comment by jenting** [comment]
@machine424 any PR is welcome~
