### ISSUE TITLE
`helm upgrade` does not upgrade the CRDs

### ISSUE THREAD

**Issue by jenting** [vmware-tanzu/helm-charts#197]
**What steps did you take and what happened:**

When performs `helm upgrade`, the Velero CRDs do not upgrade.

```
helm install -f values.yaml --version 2.12.2
kubectl get crds backupstoragelocations.velero.io -oyaml > backupstoragelocations.velero.io.2.12.2.yaml

helm upgrade -f values.yaml --version 2.14.4
kubectl get crds backupstoragelocations.velero.io -oyaml > backupstoragelocations.velero.io.2.14.4.yaml

diff backupstoragelocations.velero.io.2.12.2.yaml backupstoragelocations.velero.io.2.14.4.yaml
```

**What did you expect to happen:**

The CRDs be upgraded when performing `helm upgrade`.

**The output of the following commands will help us better understand what's going on**:

N/A

**Anything else you would like to add:**

N/A

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version:
  - helm2 (use `helm list`):
  - helm3 (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by carlisia** [comment]
> Should the velero-crd chart version equal to velero chart version even if the velero-crd chart does not have any changes?
This would be a maintenance nightmare.

> Or we should keep the velero-crd version sync with Velero released version since generally the time to change the velero-crd chart is the update the Velero CRDs manifest when the new Velero is released.

This seems reasonable. The thing that I'm wondering is how to specify what version to upgrade to when doing `helm upgrade`. Will it always means upgrade to latest?

**Comment by jenting** [comment]
The thing that I'm wondering is how to specify what version to upgrade to when doing `helm upgrade`. Will it always means upgrade to latest?

By default, helm will upgrade to the latest unless the user provided the chart version to the `helm upgrade --version=<specific_chart_version`.
BTW, the user has to run `helm repo update` before helm install/upgrade to get the latest release chart.
