### ISSUE TITLE
Use a github token from a bot instead of the one for @carlisia

### ISSUE THREAD

**Issue by cpanato** [vmware-tanzu/helm-charts#20]
the token that is being used to release the charts (https://github.com/vmware-tanzu/helm-charts/releases) are from @carlisia a good practice is to use a bot github account, so we dont need to use personal tokens instead we use the token from the bot

/cc @carlisia @nrb

**Comment by carlisia** [comment]
@nrb do we have a bot account for anything?

**Comment by nrb** [comment]
I'm not aware of a Tanzu one, but that doesn't mean there isn't one somewhere.

**Comment by carlisia** [comment]
I sorta forgot about this but looking into it this/next week.

**Comment by jenting** [comment]
I think we could use `GITHUB_TOKEN` secret on behalf of release the helm chart by [github-actions](https://github.com/apps/github-actions), ref to https://docs.github.com/en/free-pro-team@latest/actions/reference/authentication-in-a-workflow

**Comment by carlisia** [comment]
Ok, let's try. Let me know if you need anything.

**Comment by jenting** [comment]
🤔 Not released, I'll look into it to check what's wrong.

**Comment by jenting** [comment]
It works, @carlisia you could remove your personal token now 😏
