### ISSUE TITLE
Any plan to update API version to v1?

### ISSUE THREAD

**Issue by Makovec** [vmware-tanzu/helm-charts#203]
Hi,
please.

**Describe the problem/challenge you have**
When running `helm` with latest minikube configuration:

```
╰─ minikube start
😄  minikube v1.16.0 on Darwin 11.1
✨  Automatically selected the hyperkit driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

I receive warnings and nothing happen:

```
W0118 22:09:45.018506   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.031113   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.042564   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.053022   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.074617   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.087791   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.097837   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.139409   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.154605   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.164905   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W0118 22:09:45.176159   57397 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```
**Describe the solution you'd like**
I'd like to have CRDs updated to v1.

**Environment:**

- helm version (use `helm version`): Version:"v3.4.0"
- helm chart version and app version:
  - helm3 (use `helm list -n <YOUR NAMESPACE>`): 
NAME  	NAMESPACE	REVISION	UPDATED                             	STATUS	CHART        	APP VERSION
velero	velero   	1       	2021-01-18 22:09:47.306611 +0100 CET	failed	velero-2.14.5	1.5.2
- Kubernetes version (use `kubectl version`): 1.20.0
- Kubernetes installer & version:
- Cloud provider or hardware configuration: minikube
- OS (e.g. from `/etc/os-release`): macOS

**Comment by jenting** [comment]
Thank you for the reporting, we will investigate how to check the kube-apiserver to support both v1beta1 and v1 version.
Also, to have a default version (v1beta1 maybe).

**Comment by isaac88** [comment]
@jenting I'm currently using Kubernetes 1.19 
Do you know if it's safe to make the upgrade the velero crd from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1 ?

Thanks

**Comment by jenting** [comment]
> @jenting I'm currently using Kubernetes 1.19
> Do you know if it's safe to make the upgrade the velero crd from apiextensions.k8s.io/v1beta1 to apiextensions.k8s.io/v1 ?
> 
> Thanks

At Kubernetes 1.19, the kube-apiserver preferred version is `apiextensions.k8s.io/v1`.
The Kubernetes supports conversion between different API versions https://book.kubebuilder.io/multiversion-tutorial/conversion-concepts.html. So, `apiextensions.k8s.io/v1beta1` will convert to `apiextensions.k8s.io/v1` by kube-apiserver webhook.

If we want to change to CRD manifest, we have to change this line https://github.com/vmware-tanzu/velero/blob/9e29e50/hack/update-generated-crd-code.sh#L49 from `v1beta1` to `v1`.

**Comment by jenting** [comment]
Ref to https://github.com/vmware-tanzu/velero/pull/3614#issuecomment-805040541

**Comment by sharkymcdongles** [comment]
> Thank you for the reporting, we will investigate how to check the kube-apiserver to support both v1beta1 and v1 version.
> Also, to have a default version (v1beta1 maybe).

The easiest way to do this is to use the built-in functions for checking capabilities.

For example something like this should work:
```
{{- define "velero.crd.apiVersion" -}}
  {{- if (.Capabilities.APIVersions.Has "apiextensions.k8s.io/v1") -}}
      {{- print "apiextensions.k8s.io/v1" -}}
  {{- else -}}
    {{- print "apiextensions.k8s.io/v1beta1" -}}
{{- end -}}
```

Unfortunately it doesn't work because CRDs don't support templating via helm. :/ So the only solution is to change it for everyone from a certain version. Helm also won't upgrade CRDs, so you will need manual actions to do this with kubectl apply.

**Comment by jenting** [comment]
> Unfortunately it doesn't work because CRDs don't support templating via helm.

Yes, a nightmare :dizzy_face:
