### ISSUE TITLE
Drop Helm v2 support and use Helm v3

### ISSUE THREAD

**Issue by cpanato** [vmware-tanzu/helm-charts#206]
**Describe the problem/challenge you have**
Helm v2 is EOL since November 2020, there is no more support and users should migrate to helm v3

Items we need to do in the repo to remove the support

- [x] Remove the github action job for helm v2
- [x] migrate the chart to be 100% helm v3 (Done already!)
- [x] write a readme to alert users that helm v2 is removed

/cc @carlisia @jenting

**Comment by carlisia** [comment]
Yeay for this! 🎉
