### ISSUE TITLE
`generated` field on vmware-tanzu repository's index.yaml manifest doesn't get updated

### ISSUE THREAD

**Issue by martinezleoml** [vmware-tanzu/helm-charts#207]
**What steps did you take and what happened:**
We're using fluxcd.io (v2) to automate our helm release deployments & upgrades.
Flux regularly watches vmware-tanzu helm repository (by fetching https://vmware-tanzu.github.io/helm-charts/index.yaml manifest) and relies on the `generated` field to determine if the repository got updated. If it's the case, flux downloads latest charts and updates according helm releases.

**What did you expect to happen:**
When a new chart is published to the repository, the index.yaml `generated` field should be updated. 
Currently the value is stuck to `generated: "2019-12-18T18:07:47.212339875Z"` whereas new chart revisions have been added since.

**The output of the following commands will help us better understand what's going on**:
N/A

**Anything else you would like to add:**
Seems to be related with helm/chart-releaser#90

**Comment by martinezleoml** [comment]
Seems to be related with this issue from chart-releaser: https://github.com/helm/chart-releaser/issues/90

**Comment by jenting** [comment]
The new version https://github.com/helm/chart-releaser/releases/tag/v1.2.0 released, we should update CI to make the `generated` field be updated.

**Comment by jenting** [comment]
I had verified that the latest release, `generated` field gets updated :tada:
