### ISSUE TITLE
Pod volume backup failed

### ISSUE THREAD

**Issue by bayerb** [vmware-tanzu/helm-charts#230]
**What steps did you take and what happened:**
After setting up velero on AKS, and running the command:
`velero backup logs balazs-teszt-backup4`

the backup is in PartiallyFailed phase, and the logs show the following error:

`velero backup logs balazs-teszt-backup4|grep error

time="2021-03-09T08:32:13Z" level=info msg="1 errors encountered backup up item" backup=velero/balazs-teszt-backup4 logSource="pkg/backup/backup.go:427" name=ugribugri-nexus-0
time="2021-03-09T08:32:13Z" level=error msg="Error backing up item" backup=velero/balazs-teszt-backup4 error="pod volume backup failed: error running restic backup, stderr=Fatal: unable to open config file: blob.GetProperties: storage: service returned error: StatusCode=404, ErrorCode=404 The specified blob does not exist., ErrorMessage=no response body was available for error status code, RequestInitiated=Tue, 09 Mar 2021 08:32:12 GMT, RequestId=4c0d9393-501e-0074-71be-1411e9000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=\nIs there a repository at the following location?\nazure:backup:/restic/balazs-teszt\n: exit status 1" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/restic/backupper.go:179" error.function="github.com/vmware-tanzu/velero/pkg/restic.(*backupper).BackupPodVolumes" logSource="pkg/backup/backup.go:431" name=ugribugri-nexus-0`

**What did you expect to happen:**
backup is succesfull

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
On the azure storage account I see backup related files appeared. It looks like everything is backud up except the pod volume.

**Environment:**

- helm version (use `helm version`): v3.0.2
- helm chart version and app version: velero-2.15.0, 1.5.3
  - helm2 (use `helm list`):
  - helm3 (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`): Major:"1", Minor:"19", GitVersion:"v1.19.3"
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): ubuntu 18.04.4 LTS

**Comment by bayerb** [comment]
Not helm chart related issue.

**Comment by liangway** [comment]
Same here, any update on this issue?
