### ISSUE TITLE
Make the velero-restic-restore-helper init-container configurable in values.yaml

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/helm-charts#24]
I would like to be able to configure the velero-restic-restore-helper init-container in values.yaml as part of the helm installation run.

While the image.repository setting is taken into account in assembling the velero image path, the velero-restic-restore-helper init-container image name is not affected by it. Customisation of the full qualified image name can only be done via a ConfigMap (as described here, https://velero.io/docs/master/restic/) after the fact.

This would simplify the restic based setup significantly.

Reported by: @thabach
Original issue: https://github.com/helm/charts/issues/18844

**Comment by TJM** [comment]
It appears to me that this is already here, using the configmaps, but the example (comment) has the wrong image url.

https://github.com/vmware-tanzu/helm-charts/blob/ccb3719638ae7c743114ab73d2d016aae0603831/charts/velero/values.yaml#L213-L218

We found the image should actually be something like `velero/velero-restic-restore-helper:v1.2.0`

~tommy
