### ISSUE TITLE
CRDs are not in sync with `velero` v1.6.0

### ISSUE THREAD

**Issue by tobiasgiese** [vmware-tanzu/helm-charts#247]
**What steps did you take and what happened:**

After deploying the latest `velero` version v1.6.0 with the helm-chart, we discovered that the CRDs are not the ones from the velero repository.
Is it intended, that CRDs are not the same? Or is there some sync script?
At least `spec.subresources` of the CRD `downloadrequests.velero.io` is missing.

**What did you expect to happen:**

That the CRDs from the `velero` repository are in sync.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

What we did to clarify that the CRDs differ is:

```bash
# in directory ~/projects/github.com/vmware-tanzu/velero
for i in config/crd/bases/*; do
  diff -u $i ../helm-charts/charts/velero/crds/$(basename $(echo $i | sed 's/velero.io_//'))
done
```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version:
  - helm2 (use `helm list`):
  - helm3 (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by jenting** [comment]
Oops, I forgot to make the CRDs in sync 🙀
