### ISSUE TITLE
Change GH Action to auto add reviewers to PRs

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/helm-charts#253]

**Comment by jenting** [comment]
It's there already, isn't it?
https://github.com/vmware-tanzu/helm-charts/blob/main/.github/workflows/auto_assign_prs.yml
https://github.com/vmware-tanzu/helm-charts/blob/main/.github/auto_assign.yml

**Comment by carlisia** [comment]
Yes, you are right!

I want to change it to use a new one we added to the Velero repo, after it starts working properly. Hopefully this PR will make it work: https://github.com/vmware-tanzu/velero/pull/3712.

**Comment by jenting** [comment]
> Yes, you are right!
> 
> I want to change it to use a new one we added to the Velero repo, after it starts working properly. Hopefully this PR will make it work: [vmware-tanzu/velero#3712](https://github.com/vmware-tanzu/velero/pull/3712).

@carlisia I saw the https://github.com/vmware-tanzu/velero/pull/3712 merged. Would you like to file a PR here to use a new one?

**Comment by carlisia** [comment]
Thanks for checking. That one didn't fix it. I'm waiting on this one, and please merge it if it looks good to you: https://github.com/vmware-tanzu/velero/pull/3743.

**Comment by jenting** [comment]
> Thanks for checking. That one didn't fix it. I'm waiting on this one, and please merge it if it looks good to you: [vmware-tanzu/velero#3743](https://github.com/vmware-tanzu/velero/pull/3743).

Merged!

**Comment by carlisia** [comment]
@jenting if you want to get this taken care of please go ahead. Otherwise I'll open a PR tomorrow.

**Comment by jenting** [comment]
I think this one is finished, close it.
