### ISSUE TITLE
How can i create helm release with multiple backup storage locations?

### ISSUE THREAD

**Issue by badalk** [vmware-tanzu/helm-charts#254]
**What steps did you take and what happened:**

I am trying to install velero with multiple backup storage locations, each having its own service principal with Azure provider.

**What did you expect to happen:**

 Is this possible to do so with helm chart. If not what is the alternative? Current process to do so requires mounting the volumes with secrets (embedding the service principal details and azure subscription and resourcegroup) in the deployment. But with this helm helm chart its not in our control and doesn't look like we can provide multiple values for backupstorage locations each having its own service principal (that is supported in velero 1.6.0)

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version:
  - helm2 (use `helm list`):
  - helm3 (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by jenting** [comment]
I think we should revisit PR #51 again.

**Comment by jenting** [comment]
Hmmm... it's not easy to make it backward-compatible.
I need more time on this.

Or other contributors, feel free to open PR if you have a good idea on this one.

**Comment by badalk** [comment]
i wished if the kustomize approach the team is working on is available to use. Will help us to keep the chart in central location / repository and just supply values from each cluster configuration repo and sync helm-release with helm operator and flux !!

**Comment by jenting** [comment]
No, we won't choose kustomize as our solution.

You could use kustomize + GitOps tool in your repo and add customize value to overwrite the default.
