### ISSUE TITLE
Restic Daemonset unschedulable after upgrade to 2.19.0

### ISSUE THREAD

**Issue by koalalorenzo** [vmware-tanzu/helm-charts#256]
**What steps did you take and what happened:**
After deploying the latest version `2.19.0` (previously was `2.17.1`), some of the pods (not all of them) deployed by the rustic DaemonSet are unschedulable with the error:

```
Events:
  Type     Reason             Age                    From                Message
  ----     ------             ----                   ----                -------
  Warning  FailedScheduling   4s (x5 over 98s)       default-scheduler   0/9 nodes are available: 1 node(s) didn't match node selector, 8 Insufficient cpu.
  Normal   NotTriggerScaleUp  32s                cluster-autoscaler  pod didn't trigger scale-up: 3 node(s) didn't match node selector
```

We had the same issue with a brand new deployment with `2.19.0`.

**What did you expect to happen:**

I did expect the helm release to deploy successfully.

**Environment:**

- helm version (use `helm version`):  3.5.4
- helm chart version and app version:
  - helm3 (use `helm list -n <YOUR NAMESPACE>`):`velero	velero   	6       	2021-04-22 15:14:17.619093213 +0000 UTC	failed	velero-2.19.0	1.6.0`
- Kubernetes version (use `kubectl version`): `1.18` (`1.18.16-gke.502`)
- Kubernetes installer & version: 1.18
- Cloud provider or hardware configuration: Google Cloud Platform (GKE) 14 nodes (n2-standard-4) 56CPU 224GB ram available
- OS (e.g. from `/etc/os-release`): Container-optimised OS with Docker (cos)

**Comment by koalalorenzo** [comment]
We tried to downgrade to `2.18.2` and `2.17.2` with the same result.

**Comment by jenting** [comment]
I think it possibly due to we increase the default CPU/memory requests and limits #232.
Ref to https://velero.io/docs/v1.6/customize-installation/#customize-resource-requests-and-limits
You could decrease the default CPU/memory requests and limits to make it work.

**Comment by koalalorenzo** [comment]
@jenting Thanks for your reply! 
Sadly the Node had 13GB of free memory and 4 CPU cores... which is why we raised this issue!

**Comment by jenting** [comment]
Did decrease the CPU/Memory request/limit solves the problem?

**Comment by koalalorenzo** [comment]
Not really. We "solved" the issue by draining and recreating the nodes.

**Comment by jenting** [comment]
From the log, it more like the CPU resource is not enough _or_ the node selector is incorrect.
```
0/9 nodes are available: 1 node(s) didn't match node selector, 8 Insufficient cpu.
pod didn't trigger scale-up: 3 node(s) didn't match node selector
```

I did compare `2.17.1` to `2.19.0`, the change related to this is we set the default CPU/memory request/limit.
We did not enhance/fix something related to the node selector.

**Comment by koalalorenzo** [comment]
We bumped the Node memory and CPU and that "fixed" the issue (meaning it made them happy). It is not really a solution as there was clearly space, but I suppose now that this might not be an issue of the chart, but of the Kubernetes. 

I am happy to either keep this open, but at the same time feel free to close it 👍 
BTW, Thank you so much for maintaining the helm charts!!!

**Comment by jenting** [comment]
Good to know, glad you find a workaround to make it work.
I'd prefer to close it.
