### ISSUE TITLE
Error signature version

### ISSUE THREAD

**Issue by laurent6** [vmware-tanzu/helm-charts#265]
Hi, 

How we can specify was signature version ?  with this helm chart we've got this message: 

```
`time="2021-05-17T16:40:47+02:00" level=error msg="Error listing backups in backup store" backupLocation=aws 
controller=backup-sync error="rpc error: code = Unknown desc = SignatureDoesNotMatch: The request signature we calculated 
does not match the signature you provided. Check your key and signing method.\n\tstatus code: 403, request id: 
txf9f58817d4e54a54964d9-0060a2806f, host id: txf9f58817d4e54a54964d9-0060a2806f" error.file="/go/src/velero-plugin-for-
aws/velero-plugin-for-aws/object_store.go:361" error.function="main.(*ObjectStore).ListCommonPrefixes" 
logSource="pkg/controller/backup_sync_controller.go:182"

`
```

**Comment by jenting** [comment]
Could you elaborate more in detail? 
It'd be good if you could follow the [bug  template](https://github.com/vmware-tanzu/helm-charts/blob/main/.github/ISSUE_TEMPLATE/bug_report.md) or [feature request template](https://github.com/vmware-tanzu/helm-charts/blob/main/.github/ISSUE_TEMPLATE/feature-enhancement-request.md).

**Comment by laurent6** [comment]
---
name: Error signature
about: when i use this chart i have lot of error to openIO connection. 

---

**What steps did you take and what happened:**
I use helm chart and deploy it by flux.io. All services start


```
root@dev-master1:~# kubectl get all -n velero-system 
NAME                          READY   STATUS    RESTARTS   AGE
pod/restic-ggsv7              1/1     Running   0          16h
pod/restic-ggxsp              1/1     Running   0          16h
pod/restic-nlsrd              1/1     Running   0          16h
pod/restic-zk5rj              1/1     Running   0          16h
pod/velero-744485fd97-wjkmg   1/1     Running   0          16h

NAME             TYPE        CLUSTER-IP    EXTERNAL-IP   PORT(S)    AGE
service/velero   ClusterIP   X.X.X.X   <none>        8085/TCP   18h

NAME                    DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/restic   4         4         4       4            4           <none>          18h

NAME                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/velero   1/1     1            1           18h

NAME                                DESIRED   CURRENT   READY   AGE
replicaset.apps/velero-744485fd97   1         1         1       16h
replicaset.apps/velero-9694c75d4    0         0         0       18h
root@dev-master1:~# 


```
I test connexion into each node with `s3cmd` tools. It's working. ( key and access aws are correct ) . 
 
**What did you expect to happen:**

it's not working.  I have olot of error in log pod velero. 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
https://gist.github.com/laurent6/9c837978bedb64544fb35645bcc28da0.js

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- helm version (use `helm version`): flux version 0.13.4 hrelm -> version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
```
`NAME  	NAMESPACE    	REVISION	UPDATED                                	STATUS  	CHART        	APP VERSION
velero	velero-system	3       	2021-05-17 14:30:03.196225204 +0000 UTC	deployed	velero-2.15.0	1.5.3    `
```
- Kubernetes version (use `kubectl version`):
```
root@dev-master1:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"
```
- Kubernetes installer & version:

- OS (e.g. from `/etc/os-release`):
```
root@dev-master1:~# lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

```

**Comment by laurent6** [comment]
My mistake. In velero client I d'idn't add --storage-location value
