### ISSUE TITLE
Job upgradeCRDs

### ISSUE THREAD

**Issue by Arturx47** [vmware-tanzu/helm-charts#270]
**What steps did you take and what happened:**
i set to false and it crashes the code....
[A clear and concise description of what the bug is, and what commands you ran.)

**What did you expect to happen:**
to get rid of the job...
i would expect to set to upgradeCRDs: false and then don't deploy the job..

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 2.21.0
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`): 1.19.6 and 1.19.9
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Vmware Tanzu and GKE
- OS (e.g. from `/etc/os-release`):

**Comment by jenting** [comment]
I did a quick test on set the `upgradeCRDs` to `false`, the `helm template` does not includes the upgrade Job anymore.
Could you elaborate more?

**Comment by Arturx47** [comment]
Well it did work but only after removing helm hooks...we use pulumi to mange the code...
https://github.com/pulumi/pulumi-kubernetes/issues/555
Thank you
