### ISSUE TITLE
Deprecated `apiextensions.k8s.io/v1beta1` CustomResourceDefinition

### ISSUE THREAD

**Issue by sagar-jadhav** [vmware-tanzu/helm-charts#273]
**What steps did you take and what happened:**
```
helm install velero --namespace velero --version 2.14.7 vmware-tanzu/velero
```

_Output:_

```
W0607 00:18:02.086809   84707 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**What did you expect to happen:**
Installation should successful without  above mentioned `warnings`

**Environment:**

- helm version (use `helm version`): helm3
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):  2.14.7
- Kubernetes version (use `kubectl version`): v1.19
- Client OS: Ubuntu

**Comment by sagar-jadhav** [comment]
Team As a fix api version should be changed from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1` in following CustomResourceDefinition's:

- charts/velero/crds/volumesnapshotlocations.yaml
- charts/velero/crds/deletebackuprequests.yaml
- charts/velero/crds/serverstatusrequests.yaml
- charts/velero/crds/resticrepositories.yaml
- charts/velero/crds/downloadrequests.yaml
- charts/velero/crds/podvolumerestores.yaml
- charts/velero/crds/backupstoragelocations.yaml
- charts/velero/crds/podvolumebackups.yaml
- charts/velero/crds/schedules.yaml
- charts/velero/crds/backups.yaml
- charts/velero/crds/restores.yaml

**Comment by jenting** [comment]
Duplicated to #203.

**Comment by sagar-jadhav** [comment]
Thank you @jenting for marking issue as `duplicate`. I was not aware about the other issue.

**Comment by jenting** [comment]
Since it's duplicated, I'll close it first.
Thank you for the reporting.
