### ISSUE TITLE
#BUG# Image version tag 1.6.2 is not available and fails the velero deployment for the file helm-charts/charts/velero/values.yaml

### ISSUE THREAD

**Issue by tarundmsharma** [vmware-tanzu/helm-charts#288]
While deploying velero using the image version as 1.6.2 the deployment fails 
[A clear and concise description of what the bug is, and what commands you ran.)

**What did you expect to happen:**
deployment of velero pod in kubernetes cluster

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
The issue was resolved by using the Image version as 1.2.0, same is available in the docker hub.

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by jenting** [comment]
Could you please provide the detailed log?

**Comment by jenting** [comment]
Close it, I can make the deployment succeeded, feel free to reopen it if you have any problems.
