### ISSUE TITLE
kuberntes 1.22 does not support CRD apiextensions.k8s.io/v1beta1 anymore

### ISSUE THREAD

**Issue by damoon** [vmware-tanzu/helm-charts#289]
**What steps did you take and what happened:**
i want to install velero via the helm chart

**What did you expect to happen:**
it installs

**Anything else you would like to add:**
kubernetes docs: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22
example crd: https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/crds/backups.yaml#L3

**Environment:**

- helm version (use `helm version`): v3.6.3
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): vmware-tanzu/velero 2.23.5
- Kubernetes version (use `kubectl version`): 1.22
- Kubernetes installer & version: kuebadm
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`): ubuntu 20.04 + hwe kernel

**Comment by jenting** [comment]
Duplicate to #203.
We're working on bumping to `apiextensions.k8s.io/v1` version at vmware-tanzu/velero and will be target release at v1.6.3.
Once the v1.6.3 is released, we'll bump helm chart CRD to `apiextensions.k8s.io/v1``apiextensions.k8s.io/v1`.

**Comment by jenting** [comment]
Close this issue since it's duplicate to #203.
