### ISSUE TITLE
[helm-chart] Velero backupStorageLocations configuration

### ISSUE THREAD

**Issue by WenLongSun19** [vmware-tanzu/helm-charts#299]
**What steps did you take and what happened:**
I'm testing cross-cluster migration based on this case [#1899](https://github.com/vmware-tanzu/velero/issues/1899).
But I can't find the ** BackupStorageLocations** configuration in helm chart. How do I set it up correctly?

**What did you expect to happen:**
Configure Velero to support cross-cluster migration

**Environment:**

- helm version (use `helm version`): 3.5.4
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):chart: v2.23.6. app version: v1.6.3
- Kubernetes version (use `kubectl version`): v1.20.10
- Kubernetes installer & version: RKE 2.5.9
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Ubuntu 20.04.2 LTS

**Comment by jenting** [comment]
Related to https://github.com/vmware-tanzu/helm-charts/issues/294#issuecomment-915687776

**Comment by WenLongSun19** [comment]
Thank you @jenting , I have configured successfully with only a backupStorageLocation. But my question is how to set multiple backupStorageLocatoins in the helm chart

**Comment by jenting** [comment]
> Thank you @jenting , I have configured successfully with only a backupStorageLocation. But my question is how to set multiple backupStorageLocatoins in the helm chart

There is issue #254 about multiple backupStorageLocations in the helm chart.
We haven't find time to add because we need to deal with the backward-compatible.

Free free to contribute it if you have time :smiley:

**Comment by jenting** [comment]
I'd prefer to close this issue if the leftover question you have is the multiple backup storage locations in the helm chart.
Thank you.
