### ISSUE TITLE
Migrate Velero Helm chart away from github.com/helm/charts

### ISSUE THREAD

**Issue by robinkb** [vmware-tanzu/helm-charts#3]
**Describe the problem/challenge you have**

With the release of Helm 3, Helm 2 has transitioned into maintenance mode, and so has the Helm Charts GitHub project. As of November 13th, new charts are no longer accepted. After May 13th, 2020, only security fixes will be accepted, and the Helm Charts GitHub project will be delisted from [Helm Hub](https://hub.helm.sh/). Finally, on November 13th, 2020, the Helm Charts GitHub will be archived and marked obsolete.

~~Another, more personal issue is that it is very difficult and time-consuming to get pull requests merged for the Helm Charts project. I am personally waiting for two pull requests: [one that fixes Azure support](https://github.com/helm/charts/pull/18472), and [one that upgrades Velero to 1.2.0](https://github.com/helm/charts/pull/18492). Neither pull requests has seen any recent activity. I am currently forced to maintain my own fork with those two fixes merged to start using Velero.~~

I checked again, and Azure fixes have actually been merged in another PR. The other issue with the version bump is fixable on my end. Still, the issue of deprecation remains.

**Describe the solution you'd like**

The Velero project needs to migrate its Helm chart sources to this git repository, and host the packaged chart on another chart repository, probably one hosted by VMware.

**Comment by cpanato** [comment]
this is done @carlisia @nrb

**Comment by carlisia** [comment]
The Velero chart now lives in the repo, as addressed by https://github.com/vmware-tanzu/helm-charts/pull/8, so this issue is done.

Deprecation of original repo/chart will be tracked here: https://github.com/vmware-tanzu/helm-charts/issues/6
