### ISSUE TITLE
Restic daemon set failed to communicate with Azure provider

### ISSUE THREAD

**Issue by sathishkumarkrishnasamy** [vmware-tanzu/helm-charts#30]
In Present helm chart restic-daemonset.yaml obtaining azure credentials from sercret and exposed as environment variable.

          {{- if and .Values.credentials.useSecret (eq $provider "azure") }}
          envFrom:
            - secretRef:
                name: {{ include "velero.secretName" . }}
          {{- end }}

But velero image velero/velero:v1.2.0 expects the credential from  env AZURE_CREDENTIALS_FILE /credentials/cloud

We have to modify the  restic-daemonset.yaml to make it to work,

  {{- if .Values.deployRestic }}
  {{- $provider := .Values.configuration.provider -}}
  apiVersion: apps/v1
  kind: DaemonSet
  metadata:
     name: restic
     labels:
    app.kubernetes.io/name: {{ include "velero.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "velero.chart" . }}
spec:
  selector:
    matchLabels:
      name: restic
  template:
    metadata:
      labels:
        name: restic
        app.kubernetes.io/name: {{ include "velero.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        helm.sh/chart: {{ include "velero.chart" . }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.serviceAccount.server.create }}
      serviceAccountName: {{ include "velero.serverServiceAccount" . }}
      {{- end }}
      securityContext:
        runAsUser: 0
      {{- if .Values.restic.priorityClassName }}
      priorityClassName: {{ include "velero.restic.priorityClassName" . }}
      {{- end }}
      volumes:
        {{- if .Values.credentials.useSecret }}
        - name: cloud-credentials
          secret:
            secretName: {{ include "velero.secretName" . }}
        {{- end }}
        - name: host-pods
          hostPath:
            path: {{ .Values.restic.podVolumePath }}
        - name: scratch
          emptyDir: {}
        {{- if .Values.restic.extraVolumes }}
        {{- toYaml .Values.restic.extraVolumes | nindent 8 }}
        {{- end }}
      containers:
        - name: velero
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /velero
          args:
            - restic
            - server
          volumeMounts:
            {{- if .Values.credentials.useSecret }}
            - name: cloud-credentials
              mountPath: /credentials
            {{- end }}
            - name: host-pods
              mountPath: /host_pods
              mountPropagation: HostToContainer
            - name: scratch
              mountPath: /scratch
            {{- if .Values.restic.extraVolumeMounts }}
            {{- toYaml .Values.restic.extraVolumeMounts | nindent 12 }}
            {{- end }}
          env:
            - name: VELERO_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: VELERO_SCRATCH_DIR
              value: /scratch
            {{- if and .Values.credentials.useSecret (or (eq $provider "aws") (or (eq $provider "gcp") (eq $provider "azure"))) }}
            {{- if eq $provider "aws" }}
            - name: AWS_SHARED_CREDENTIALS_FILE
            {{- else if eq $provider "gcp"}}
            - name: GOOGLE_APPLICATION_CREDENTIALS
            {{- else }}
            - name: AZURE_CREDENTIALS_FILE
            {{- end }}
              value: /credentials/cloud
            {{- end }}
            {{- if eq $provider "minio" }}
            - name: AWS_SHARED_CREDENTIALS_FILE
              value: /credentials/cloud
            {{- end }}
          securityContext:
            privileged: {{ .Values.restic.privileged }}
          {{- with .Values.restic.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.restic.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}

**Comment by fredgate** [comment]
Yes this is blocking : velero can not backup Azure files using Restic.
There is a opened pull request #46 opened since January 30.

**Comment by jenting** [comment]
Thanks, I could backup with restic to Azure blob container with this PR.
