### ISSUE TITLE
velero-plugin-for-microsoft-azure: provide credentials as individual variable

### ISSUE THREAD

**Issue by HighWatersDev** [vmware-tanzu/helm-charts#304]
Hi,

I'm trying to install velero using Helm and STORAGE_ACCOUNT_ACCESS_KEY. The only option I see in the docs is to provide the credential as `./credentials-velero` file which works just fine. But when I try to set the same credential using `--set credentials.secretContents.cloud="AZURE_STORAGE_ACCOUNT_ACCESS_KEY=<base64 value>\nAZURE_CLOUD_NAME=AzurePublicCloud"`, it doesn't work. Is there a way to do this outside of using `--set-file` option?

**Vote on this issue!**

This is an invitation to the Velero community to vote on issues, you can see the project's [top voted issues listed here](https://github.com/vmware-tanzu/velero/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).  
Use the "reaction smiley face" up to the right of this comment to vote.

- :+1: for "I would like to see this bug fixed as soon as possible"
- :-1: for "There are more important bugs to focus on right now"

**Comment by zubron** [comment]
Hi @HighWatersDev. This appears to be specific to the behavior of `--set`  and is not specific to the Velero Helm chart. I tried this out locally and the new lines were not included in the secret contents, but I was able to make it work by explicitly including new lines in the value.
```
helm install velero-test vmware-tanzu/velero --dry-run --debug \
--set credentials.secretContents.cloud="AZURE_TEST=foo
AZURE_TEST=bar"
```
This behavior is likely dependent on the quoting and shell that is being used. For ease and portability, I would recommend continuing to use the `--set-file` approach or write the contents to a `values.yaml` file that you can use during the chart installation.

I'm going to close this as I don't think there's any action to take on our side.

**Comment by HighWatersDev** [comment]
Hi @zubron ,

Thanks for the. feedback. I'm sorry I wasn't clear on the issue. I'm trying to use `--set` flag and provide credentials using storage_account_access_key:

```
helm upgrade --install velero vmware-tanzu/velero --namespace velero --create-namespace --set credentials.secretContents.cloud="<secret>"
```

This command creates the same secret as the one created using `--set-file=./credentials-velero` with only difference in name:
- with `--set-file` the name of secret is **credentials-velero**
- with `--set` the name of secret is **velero**

If I compare secrets they are identical. If I look at logs, I see the following:

```
level=error msg="Error getting backup store for this location" backupLocation=azure controller=backup-sync error="rpc error: code = Unknown desc = azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/<...>/resourceGroups/<...>/providers/Microsoft.Storage/storageAccounts/<...>/listKeys?%24expand=kerb&api-version=2019-06-01: StatusCode=400 -- Original Error: adal: Refresh request failed. Status Code = '400'. Response body: {\"error\":\"invalid_request\",\"error_description\":\"Multiple user assigned identities exist, please specify the clientId / resourceId of the identity in the token request\"}" error.file="/go/src/velero-plugin-for-microsoft-azure/velero-plugin-for-microsoft-azure/object_store.go:217" error.function=main.getStorageAccountKey logSource="pkg/controller/backup_sync_controller.go:175"
```

From what I could tell, it's treating this secret as AAD pod identity and not as storage_account_access_key.
