### ISSUE TITLE
[Question] documentation: defining path

### ISSUE THREAD

**Issue by mrszop** [vmware-tanzu/helm-charts#307]
Hello,

I kind of having a hard time defining a specific path for my backups to s3. Currently they look like this:

```
aws s3 ls s3://BUCKET/SUBFOLDER/kubernetes/full/
                           PRE backups/
                           PRE restic/
```

How do I change the `backups/` and `restic/` path? Is this something I missed in the [values.yaml](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml)?

Next thing is, backups are created in this format `velero-dev-20210922100042/`. Are there any options to change this date? I understand the name is created via [helm chart](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/schedule.yaml#L6) and therefor like this in the s3.

Cheers

**Comment by jenting** [comment]
> How do I change the `backups/` and `restic/` path? Is this something I missed in the [values.yaml](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/values.yaml)?

The folders are create by Velero core, I don't remember we support changing the folder name.
What's the purpose you want to change it?

We could only add prefix https://github.com/vmware-tanzu/helm-charts/blob/velero-2.23.8/charts/velero/values.yaml#L164

> 
> Next thing is, backups are created in this format `velero-dev-20210922100042/`. Are there any options to change this date? I understand the name is created via [helm chart](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/schedule.yaml#L6) and therefor like this in the s3.

I don't remember Velero supports to change the timestamp format https://velero.io/docs/v1.6/how-velero-works/#scheduled-backups

**Comment by mrszop** [comment]
Hey jenting,

thanks for the fast reply.

>The folders are create by Velero core, I don't remember we support changing the folder name.
What's the purpose you want to change it?

I have no special purpose for that, but I was curious if it's possible (flexibility) and maybe I was missing an option. I'm already using a prefix.

>I don't remember Velero supports to change the timestamp format https://velero.io/docs/v1.6/how-velero-works/#scheduled-backups

Ok got it.

Thanks for making things clear,
Cheers
