### ISSUE TITLE
Velero/restic : trying to make backup everyday for each project

### ISSUE THREAD

**Issue by SmartGuyy** [vmware-tanzu/helm-charts#324]
**What steps did you take and what happened:**
I'm trying to set up this helm chart to make velero/restic backup everyday instead of comparing if volumes were changed or not and backup only if they changed.

**What did you expect to happen:**

Find a setting in values.yaml or within templates to backup everyday

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): latest
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): latest
- Kubernetes version (use `kubectl version`): latest
- Kubernetes installer & version: latest
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Linux

**Comment by SmartGuyy** [comment]
Maybe i wasn't clear enough : goal of this issue is to ask you if there is any possibility for restic to make snapshots on a daily basis no matter if there was a change in the volume or not.

I'm trying to do that because we have a Grafana dashboard called "backup-checker" and we would like to set up alarms if backups are older than 2 days but the fact that restic doesn't make a new snapshot everyday prevents us from doing that alarm as snapshots remains with the same timestamp.

**Comment by jenting** [comment]
> goal of this issue is to ask you if there is any possibility for restic to make snapshots on a daily basis no matter if there was a change in the volume or not.

For this part, I'm not 100% sure, it's better to check the restic doc to see if there is any flag to achieve.
But from my point of view, restic performs the incremental snapshot so without any change on the file system, the snapshot should not be created.
But anyway, it's better to check the restic doc to see if it's doable or not.

**Comment by SmartGuyy** [comment]
Hello @jenting, thank you for your reply. From what i see it doesn't seems to be in the spirit of Restic to allow backing up all data everyday without any mechanisms like file change detection... Which seems logical in some way as it would be expensive to scan and rebackup all data each time.

From what i saw in my investigations, this doesn't seems possible so i will close that issue.
