### ISSUE TITLE
extraEnvVars doesn't work with numerical values

### ISSUE THREAD

**Issue by brovoca** [vmware-tanzu/helm-charts#334]
**What steps did you take and what happened:**

I attempted to install Velero with an additional environment variable which I want restic to use, but it didn't work when I provided a numerical value. If I supplied `'test'` as the value, it would work.

Relevant `values.yaml` section:
```yaml
configuration:
  extraEnvVars:
    GOGC: '20'
```

**What did you expect to happen:**

Helm chart quotes all values provided through extraEnvVars.

**Environment:**

- helm version (use `helm version`): `version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}`
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):

```yaml
NAME    NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
velero  velero          34              2022-01-13 15:06:53.653052329 +0000 UTC deployed        velero-2.27.3   1.7.1
```

- Kubernetes version (use `kubectl version`):

```yaml
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"802eff1fe87ad2dd737ebbe891f30500b88beb00", GitTreeState:"clean", BuildDate:"2021-11-15T08:35:41Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version: AKS
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): N/A

**Comment by jenting** [comment]
> but it didn't work when I provided a numerical value.

How do you verify it's not working?

I did a quick check by `helm temaplte` with providing
```yaml
configuration:
  extraEnvVars:
    GOGC: '20'
```

This is the generated output
```yaml
env:
  - name: GOGC
    value: 20
```

Seems like the numerical value be generated.

**Comment by brovoca** [comment]
@jenting try to do a Helm install. `helm template` will for the most part only throw errors when the YAML syntax is incorrect.
