### ISSUE TITLE
CRDs appear OutOfSync when deployed with ArgoCD

### ISSUE THREAD

**Issue by joemiller** [vmware-tanzu/helm-charts#335]
**What steps did you take and what happened:**
Deploying Velero helm chart via ArgoCD leaves the CRDs showing as OutOfSync due to a missing label in the deployed CRDs.

![image](https://user-images.githubusercontent.com/377603/150037632-7f6c91c7-d6b0-4fc0-b16a-c6e3a0806418.png)

**What did you expect to happen:**
CRDs should not show as out of sync.

It looks like what is happening is:

1. ArgoCD syncs the helm chart which includes the CRD yaml files from the `./crds/` directory. This version of the CRDs contains a label `app.kubernetes.io/name: velero`
2. A few minutes later a k8s `Job` is spawned and runs: `/velero install --crds-only --dry-run -o yaml | /tmp/kubectl apply -f -` to install/upgrade the CRDs from the latest version in the velero binary. This version of the yaml does not contain the label. (https://github.com/vmware-tanzu/helm-charts/blob/7409442755032bdd2be574b1e3e3f39fb16271a5/charts/velero/templates/upgrade-crds.yaml#L70)
3. ArgoCD marks all of Velero's CRDs as OutOfSync.

It should be possible to workaround this issue by setting `upgradeCRDs: false` to avoid creation of the `Job` in step 2 but I am not sure what problems this may cause in the future during upgrades.

Solutions?

- I did not see a flag for `velero install` that would allow adding additional labels to the generated CRDs. If that was available the helm chart could add the same labels to the CRDs as those that were added to the files in the `./crds/` directory.

- Remove the `app.kubernetes.io/name` label from the files in the `./crds` directory of the helm chart.

**Environment:**

- helm version (use `helm version`): 3.7.2
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 2.27.0, 1.7.0
- Kubernetes version (use `kubectl version`): 1.20.8
- Kubernetes installer & version: EKS
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): ubuntu

**Comment by jenting** [comment]
> It should be possible to workaround this issue by setting `upgradeCRDs: false` to avoid creation of the `Job` in step 2 but I am not sure what problems this may cause in the future during upgrades.

If I remember correctly, for the users who use ArgoCD, they need to set up the `upgradeCRDs: false`.

Actually, I'm thinking that probably we should choose another approach to upgrade the Velero CRD instead of using a kubectl job to upgrade the Velero CRD.

**Comment by qiuming-best** [comment]
@joemiller @jenting what about we add `app.kubernetes.io/name: velero` in all upstream velero CRDs ?

**Comment by jenting** [comment]
@qiuming-best 
Sure, but why? Will adding the labels address this issue?

**Comment by qiuming-best** [comment]
@jenting 
I'm not quite sure about it. If it's a very common case could we add the label in upstream velero CRDs?
if not, as you said for the users who use ArgoCD, they need to set up the upgradeCRDs: false
or are there if has other solutions?

**Comment by jenting** [comment]
@joemiller 
> Remove the app.kubernetes.io/name label from the files in the ./crds directory of the helm chart.

We removed the label `app.kubernetes.io/name` #361 previously.
Is the issue still happening?
