### ISSUE TITLE
When serviceMonitor is enabled prometheus pod annotations should not be set

### ISSUE THREAD

**Issue by SebPlv** [vmware-tanzu/helm-charts#336]
Hello,

**What steps did you take and what happened:**
When I deploy velero with serviceMonitor enabled in values.yaml, metrics are collected twice by prometheus, once through serviceMonitor and once through prometheus pod annotations (job prometheus-pod in prometheus).

**What did you expect to happen:**
I think that if servicemonitor is enabled, annotations should not be added to the pods.
At least, the chart should give the possibility to not add podannotations when metrics and servicemonitor are enabled.

**Environment:**
- helm version : v3.3.4
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): v2.23.12
- Kubernetes version (use `kubectl version`): 1.20.11
- Kubernetes installer & version: TKGi
- Cloud provider or hardware configuration: vSphere
- OS (e.g. from `/etc/os-release`): Ubuntu

**Comment by SebPlv** [comment]
Hi @jenting 
I'm talking about prometheus scraping annotations, the follow section of the values.yaml, under metrics :

```
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8085"
  prometheus.io/path: "/metrics"
```

This annotations will instruct Prometheus to scrap pod's metrics through "prometheus-pods" target.
But if serviceMonitor is enabled Prometheus will also scrape the same metrics through "ServiceMonitor" target.

It would be great to have the possibility to not adding this annotations when "metrics.enabled" is set to true.

**Comment by jenting** [comment]
@SebPlv 
Are you willing to file a PR to fix it?

**Comment by SebPlv** [comment]
Yes, sure, I'll see what I can do.

**Comment by jenting** [comment]
> Yes, sure, I'll see what I can do.

Thank u :pray:

**Comment by jenting** [comment]
> At least, the chart should give the possibility to not add podannotations when metrics and servicemonitor are enabled.

@SebPlv 
I think #447 addressed your issue, correct?

**Comment by SebPlv** [comment]
Oh, I'm sorry, I totally forgot this issue.
Actually no because metrics.podAnnotations value is only used in velero deployment yaml, not in node-agents yaml.

I made a fix that seems to work fine. I'll provide a PR by the end of the week.
