### ISSUE TITLE
Not able to overwrite the cluster-admin role 

### ISSUE THREAD

**Issue by balu-ce** [vmware-tanzu/helm-charts#337]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
resource "helm_release" "velero" {
  name       =  "velero"
  repository = "https://vmware-tanzu.github.io/helm-charts"
  chart      = "velero"
  version    = "2.27.0"
  namespace  = "velero"

  values = [
    <<-EOT
      initContainers:
        - name: velero-plugin-for-microsoft-azure
          image: velero/velero-plugin-for-microsoft-azure:v1.2.0
          volumeMounts:
            - mountPath: /target
              name: plugins
      podLabels:
        aadpodidbinding: "${var.aks_cluster_name}-velero"
      credentials:
        useSecret: true
        secretContents:
          cloud: |
            AZURE_SUBSCRIPTION_ID=${var.subscription_id}
            AZURE_RESOURCE_GROUP=${var.aks_cluster_name}
            AZURE_CLOUD_NAME=AzurePublicCloud
      **rbac:
        create: true**
      serviceAccount:
        server:
          create: true
          name: ${kubernetes_role_binding.velero_role_binding.subject[0].name}
      configuration:
        provider: azure
        volumeSnapshotLocation:
          name: azure-default
          provider: velero.io/azure
        backupStorageLocation:
          bucket: ${azurerm_storage_container.main.name}
          config:
            resourceGroup: ${azurerm_storage_account.main.resource_group_name}
            storageAccount: ${var.storage_account_name}
      podSecurityContext:
        runAsUser: 65534
        runAsNonRoot: true
    EOT
    
}

**What did you expect to happen:**
I expect to run a velero without cluster admin role but velero-server still taking a role ref of cluster admin

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`):  3.6.0
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 2.22.0 & 1.6.0
- Kubernetes version (use `kubectl version`): 
{Major:"1", Minor:"21", GitVersion:"v1.21.7", GitCommit:"1f86634ff08f37e54e8bfcd86bc90b61c98f84d4", GitTreeState:"clean", BuildDate:"2021-11-18T00:11:23Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: Azure Provider

**Comment by jenting** [comment]
Could you please provide a more readable YAML manifest?

Also, if I understand correctly, what you want to achieve is that you want to run velero with another cluster role (other than `cluster-admin`), am I right?

**Comment by jenting** [comment]
Okay, I transfer the issue from vmware-tanzu/velero to #340.
Close this issue and use #340 to follow up.
