### ISSUE TITLE
Velero doesn't use the currently selected namespace but instead defaults to velero

### ISSUE THREAD

**Issue by sarasensible** [vmware-tanzu/helm-charts#338]
**What steps did you take and what happened:**
Kubectl uses the currently selected namespace by default to show resources, however `velero backup get` uses the hard coded namespace `velero`

**What did you expect to happen:**
`velero backup get` without specifying the namespace should default to the currently selected namespace

**The output of the following commands will help us better understand what's going on**:
[My deployment and service account yaml](https://gist.github.com/sarasensible/0ebfd90187f84e6c4f9974ae7f858e32)

**Anything else you would like to add:**
Kubectl retrieves the backups in the current namespace if I query it directly

```
kubectl get backups
NAME                AGE
argocd-secrets-v1   16h
dev-secrets-2       16h
serviceaccount-v1   16h
```
It is only the command line client which is not using the currently selected namespace.

**Environment:**

- helm version (use `helm version`):  v3.8.0
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): velero-2.27.3 , 1.7.1
- Kubernetes version (use `kubectl version`): v1.23.2
- Kubernetes installer & version: 1.21
- Cloud provider or hardware configuration:  AWS
- OS (e.g. from `/etc/os-release`):  Nodes are on Amazon Linux 2

**Comment by jenting** [comment]
It's the original Velero design, please add `--namespace` flag to each velero command _or_ setup default namespace to the velero config.
