### ISSUE TITLE
Add annotations on ServiceAccount to support IAM Roles for Service Accounts

### ISSUE THREAD

**Issue by lachlancooper** [vmware-tanzu/helm-charts#34]
Velero supports IAM Roles for Service Accounts as of v1.2.0: https://github.com/vmware-tanzu/velero/pull/1962

To actually use these the Helm chart needs to support custom `annotations` on the `ServiceAccount` resource, so a role annotation can be specified at install time. For example:
```
--set serviceAccount.server.annotations."eks\.amazonaws\.com/role-arn"=arn:aws:iam::123456789012:role/MyRoleName
```

As velero runs as `nobody`, [the pod will also need suitable permissions](https://github.com/aws/amazon-eks-pod-identity-webhook/issues/8) to read the projected token file:
```
securityContext:
  fsGroup: 65534
```

**Comment by lachlancooper** [comment]
The first part of this was solved in #29.

**Comment by galindro** [comment]
@lachlancooper are you working on it right now? I really need this feature and I can open a PR for it...

**Comment by galindro** [comment]
PR opened. Couldn't wait sorry...

**Comment by lachlancooper** [comment]
I wasn't working on it because it's covered by #41 😉

**Comment by galindro** [comment]
@lachlancooper Is there any ETA for release #41 ?
