### ISSUE TITLE
default BackupStorageLocation is not created

### ISSUE THREAD

**Issue by robertchen** [vmware-tanzu/helm-charts#342]
**What steps did you take and what happened:**
Install the velero helm chart, the pod is running fine. but no default BackupStorageLocation.  Backup failed with this error:

Validation errors:  an existing backup storage location wasn't specified at backup creation time and the server default 'default' doesn't exist. Please address this issue (see `velero backup-location -h` for options) and create a new backup. Error: BackupStorageLocation.velero.io "default" not found

$ kubectl describe BackupStorageLocation default
Error from server (NotFound): backupstoragelocations.velero.io "default" not found

**What did you expect to happen:**
the default should be there

The terraform code is this:
`configuration:
  provider: aws

  backupStorageLocation:

    name: aws
    bucket: k8s-backup-${var.vpc_project}
    prefix: ${var.k8s_cluster_name}
    config: {
      region: ${var.aws_region}
    }

  volumeSnapshotLocation:

    name: aws
    config: {
      region: ${var.aws_region}
    }`

**Environment:**

- helm version (use `helm version`):  3.7.2
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):   velero-2.27.3                   1.7.1
- Kubernetes version (use `kubectl version`):  1.17
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): ubuntu 18

**Comment by jenting** [comment]
Could you please provide your `values.yaml`? or the helm command? And the `kubectl get BackupStorageLocation -n velero`.

**Comment by robertchen** [comment]
my terraform was working for velero helm chart version 1.1.0 all the time, right now I am upgrading to 1.7.1.

```
configuration:
  provider: aws

  backupStorageLocation:

    name: aws
    bucket: k8s-backup-${var.vpc_project}
    prefix: ${var.k8s_cluster_name}
    config: {
      region: ${var.aws_region}
    }

  volumeSnapshotLocation:

    name: aws
    config: {
      region: ${var.aws_region}
    }

**Comment by jenting** [comment]
Have you configured the default field to `true`? https://github.com/vmware-tanzu/helm-charts/blob/31200ebf71e597ff602823b73cc7e50ca78ea4b3/charts/velero/values.yaml#L178

**Comment by jenting** [comment]
Lack of response, I'll close this issue now.
Feel free to reopen it if you still have concerns.
