### ISSUE TITLE
Arm architecture not supported

### ISSUE THREAD

**Issue by urdenko** [vmware-tanzu/helm-charts#349]
**What steps did you take and what happened:**
I have failed installing a helm chart using [this doc](https://aws.amazon.com/ru/blogs/containers/backup-and-restore-your-amazon-eks-cluster-resources-using-velero/)

**What did you expect to happen:**
Success deploy

**The output of the following commands will help us better understand what's going on**:
Init pod for update creds can not start. It has next logs: 
`standard_init_linux.go:228: exec user process caused: exec format error`

**Anything else you would like to add:**
I fixed problems when I added an amd64 node to my cluster and update helm value with next strings
`nodeSelector:
  kubernetes.io/arch: amd64`

**Environment:**

- helm version: 3
- helm chart version and app version: 2.28.0
- Kubernetes version: 1.21
- Cloud provider or hardware configuration: Amazon EKS
- **Architecture of all nodes: arm64**

**Comment by jenting** [comment]
Duplicate to #339
