### ISSUE TITLE
Hook removes CRD label

### ISSUE THREAD

**Issue by jemag** [vmware-tanzu/helm-charts#350]
**What steps did you take and what happened:**
- Run hook job
- Notice it deletes label from CRD

**What did you expect to happen:**
Hook does not delete label

**Anything else you would like to add:**
Currently `app.kubernetes.io/name: velero` label is part of the CRDs. However it seems the hook is using `velero install --crds-only --dry-run -o yaml` which does not generate that label.

I am guessing the cli tool should probably either generate that label or that label should be removed from the chart CRDs

**Environment:**
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 2.28.0

**Comment by jenting** [comment]
Thanks for the reporting.

**Comment by jenting** [comment]
Thanks for the feedback.

Actually, I'm thinking that probably we should choose another approach to upgrade the Velero CRD instead of using a kubectl job to upgrade the Velero CRD.

**Comment by jenting** [comment]
I think it could be fixed by the [PR](https://github.com/vmware-tanzu/velero/pull/4694).
