### ISSUE TITLE
No backup storage locations found

### ISSUE THREAD

**Issue by Revanthchowdary9** [vmware-tanzu/helm-charts#366]
logs from pod:-

time="2022-04-28T05:49:43Z" level=info msg="Starting workers" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:111" logger=controller.downloadrequest reconciler group=velero.io reconciler kicount=1
time="2022-04-28T05:49:43Z" level=error msg="No backup storage locations found, at least one is required" controller=backup-sync error="no backup storage locations found" error.file="/go/src/github.com/vmware-tae/storagelocation.go:93" error.function=github.com/vmware-tanzu/velero/internal/storage.ListBackupStorageLocations logSource="pkg/controller/backup_sync_controller.go:129"

when i described the backup i got the below error 

Phase:  Failed (run `velero backup logs nexus2` for more information)

Errors:    0
Warnings:  0

Can anyone please help me on this.

**Comment by jenting** [comment]
Please dump the backup storage locations CRs
```shell
kubectl get bsl -A
```

**Comment by Revanthchowdary9** [comment]
> Please dump the backup storage locations CRs
> 
> ```shell
> kubectl get bsl -A
> ```

[dev-user@ip- ~]$ kubectl get bsl -A
NAMESPACE   NAME      PHASE   LAST VALIDATED   AGE   DEFAULT
velero              default                                                44m

**Comment by Revanthchowdary9** [comment]
[dev-user@ip- velero]$ velero create backup nexus1 --include-namespaces nexus1
Backup request "nexus1" submitted successfully.
Run `velero backup describe nexus1` or `velero backup logs nexus1` for more details.
[dev-user@ip- velero]$ velero backup describe nexus1
Name:         nexus1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.20.11-eks-f17b81
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=20+

Phase:  FailedValidation

Validation errors:  provider aws has more than one possible volume snapshot location, and none were specified explicitly or as a default

Errors:    0
Warnings:  0

Namespaces:
  Included:  nexus1
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    <n/a>
Completed:  <n/a>

Expiration:  2022-06-01 05:03:01 +0000 UTC

**Comment by jenting** [comment]
> Validation errors: provider aws has more than one possible volume snapshot location, and none were specified explicitly or as a default

Please check the VolumeSnapshotLocation, from the log, it seems like there are multiple volume snapshot locations.
```shell
kubectl get volumesnapshotlocations.velero.io -A
```

**Comment by Revanthchowdary9** [comment]
> > Validation errors: provider aws has more than one possible volume snapshot location, and none were specified explicitly or as a default
> 
> Please check the VolumeSnapshotLocation, from the log, it seems like there are multiple volume snapshot locations.
> 
> ```shell
> kubectl get volumesnapshotlocations.velero.io -A
> ```

[dev-user@ip-~]$ kubectl get volumesnapshotlocations.velero.io -A
NAMESPACE   NAME      AGE
velero      aws       3d2h
velero      default   3d4h

**Comment by jenting** [comment]
> [dev-user@ip-~]$ kubectl get volumesnapshotlocations.velero.io -A
> 
> NAMESPACE   NAME      AGE
> 
> velero                aws       3d2h
> 
> velero                default   3d4h
> 
> 

You should delete one

**Comment by Revanthchowdary9** [comment]
> > [dev-user@ip-~]$ kubectl get volumesnapshotlocations.velero.io -A
> > NAMESPACE   NAME      AGE
> > velero                aws       3d2h
> > velero                default   3d4h
> 
> You should delete one

I Done deleted and redeployed now getting the below error.


[dev-user@ip-172-26-24-250 velero]$ velero backup describe nexus1
Name:         nexus1
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.20.11-eks-f17b81
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=20+

Phase:  Failed (run `velero backup logs nexus1` for more information)

Errors:    0
Warnings:  0

Namespaces:
  Included:  nexus1
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Velero-Native Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1.1.0

Started:    2022-05-02 10:19:47 +0000 UTC
Completed:  <n/a>

Expiration:  2022-06-01 10:19:47 +0000 UTC

Velero-Native Snapshots: <none included>
[dev-user@ip-172-26-24-250 velero]$ velero backup logs nexus1

**Comment by jenting** [comment]
Are you using AWS or MinIO?

**Comment by Revanthchowdary9** [comment]
> Are you using AWS or MinIO?

AWS

**Comment by Revanthchowdary9** [comment]
This are the pod logs 👎 

8-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:24Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:24Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:25Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:25Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:25Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:25Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:25Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:25Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:28Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:28Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:28Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:28Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:33Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:33Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:33Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:33Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:46Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/backup_sync_controller.go:175"
time="2022-05-04T07:47:53Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:53Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:47:53Z" level=error msg="Error getting a backup store" controller=download-request downloadRequest=velero/nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/download_request_controller.go:148"
time="2022-05-04T07:47:53Z" level=error msg="Reconciler error" error="unable to locate ObjectStore plugin named velero.io/aws" error.file="/go/src/github.com/vmware-tanzu/velero/pkg/controller/download_request_controller.go:149" error.function="github.com/vmware-tanzu/velero/pkg/controller.(*DownloadRequestReconciler).Reconcile" logSource="/go/pkg/mod/github.com/bombsimon/logrusr@v1.1.0/logrusr.go:121" logger=controller.downloadrequest name=nexus2-1b9cb95f-2515-448b-9568-8d296d809bdb namespace=velero reconciler group=velero.io reconciler kind=DownloadRequest
time="2022-05-04T07:48:16Z" level=error msg="Error getting backup store for this location" backupLocation=default controller=backup-sync error="unable to locate ObjectStore plugin named velero.io/aws" logSource="pkg/controller/backup_sync_controller.go:175"
time="2022-05-04T07:4

**Comment by jenting** [comment]
I'd suggest you provide the helm chart version you're using and the helm install command _or_ the values.yaml.

**Comment by Revanthchowdary9** [comment]
> I'd suggest you provide the helm chart version you're using and the helm install command _or_ the values.yaml

helm install using the values.yaml

**Comment by jenting** [comment]
> > I'd suggest you provide the helm chart version you're using and the helm install command _or_ the values.yaml
> 
> helm install using the values.yaml

Then you've to provide more detail helm install commands.

**Comment by Revanthchowdary9** [comment]
> > > I'd suggest you provide the helm chart version you're using and the helm install command _or_ the values.yaml
> > 
> > 
> > helm install using the values.yaml
> 
> Then you've to provide more detail helm install commands otherwise it's hard to _guess_ your configurations.

Okay in valuesyaml we are the passing the access key and secret

**Comment by jenting** [comment]
Okay, then I guess your command is similar as below
```shell
helm install velero \
    --namespace=velero \
    --create-namespace \
    --set-file credentials.secretContents.cloud=credentials-velero \
    --set configuration.provider=aws \
    --set configuration.backupStorageLocation.name=default \
    --set configuration.backupStorageLocation.bucket=$BUCKET \
    --set configuration.backupStorageLocation.config.region=$REGION \
    --set snapshotsEnabled=true \
    --set deployRestic=false \
    --set configuration.volumeSnapshotLocation.name=default \
    --set configuration.volumeSnapshotLocation.config.region=$REGION \
    --set initContainers[0].name=velero-plugin-for-aws \
    --set initContainers[0].image=velero/velero-plugin-for-aws:v1.4.0 \
    --set initContainers[0].volumeMounts[0].mountPath=/target \
    --set initContainers[0].volumeMounts[0].name=plugins \
    vmware-tanzu/velero
```

Please check your helm install configuration.provider name.

**Comment by Revanthchowdary9** [comment]
> Okay, then I guess your command is similar as below
> 
> ```shell
> helm install velero \
>     --namespace=velero \
>     --create-namespace \
>     --set-file credentials.secretContents.cloud=credentials-velero \
>     --set configuration.provider=aws \
>     --set configuration.backupStorageLocation.name=default \
>     --set configuration.backupStorageLocation.bucket=$BUCKET \
>     --set configuration.backupStorageLocation.config.region=$REGION \
>     --set snapshotsEnabled=true \
>     --set deployRestic=false \
>     --set configuration.volumeSnapshotLocation.name=default \
>     --set configuration.volumeSnapshotLocation.config.region=$REGION \
>     --set initContainers[0].name=velero-plugin-for-aws \
>     --set initContainers[0].image=velero/velero-plugin-for-aws:v1.4.0 \
>     --set initContainers[0].volumeMounts[0].mountPath=/target \
>     --set initContainers[0].volumeMounts[0].name=plugins \
>     vmware-tanzu/velero
> ```
> 
> Please check your helm install configuration.provider name.

yes
provider name : AWS

**Comment by jenting** [comment]
Are you using the latest helm chart?

**Comment by Revanthchowdary9** [comment]
> Are you using the latest helm chart?

yes latest one only
