### ISSUE TITLE
[velero] Helm velero integration not working with restic

### ISSUE THREAD

**Issue by Philippians413** [vmware-tanzu/helm-charts#374]
**What steps did you take and what happened:**
I want to deploy restic as a backend and upload backups to SFTP server. Want to do it through Helm.
When I specify in `values.yaml`:
```
deployRestic: true
```
and run `helm upgrade --install --create-namespace --history-max 3 --namespace velero --render-subchart-notes --wait dev-$(basename $PWD) .` then got next error:
```
Error: UPGRADE FAILED: post-upgrade hooks failed: unable to build kubernetes object for post-upgrade hook velero/templates/backupstoragelocation.yaml: error validating "": error validating data: [ValidationError(BackupStorageLocation.spec.objectStorage): missing required field "bucket" in io.velero.v1.BackupStorageLocation.spec.objectStorage, ValidationError(BackupStorageLocation.spec): missing required field "provider" in io.velero.v1.BackupStorageLocation.spec]
```
and also after that velero not deployed.

BTW, if I specify in `values.yaml`:
```
initContainers:
  - name: velero-plugin-for-csi
    image: velero/velero-plugin-for-csi:v0.2.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

configuration:
  provider: csi

deployRestic: true
```
After that velero deployed, but in velero backup I've got next error:
```
$ velero backup describe test
Name:         test
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  velero.io/source-cluster-k8s-gitversion=v1.21.6
              velero.io/source-cluster-k8s-major-version=1
              velero.io/source-cluster-k8s-minor-version=21

Phase:  FailedValidation

Validation errors:  an existing backup storage location wasn't specified at backup creation time and the server default 'default' doesn't exist. Please address this issue (see `velero backup-location -h` for options) and create a new backup. Error: BackupStorageLocation.velero.io "default" not found
```
**What did you expect to happen:**
Could somebody help me how can I configure and deploy restic with helm, make backups and upload them to SFTP server?
It's not clear for me now

**Environment:**

- helm version (use `helm version`): 3.8.2
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): Chart velero-2.29.4 (App version: 1.8.1).
- Kubernetes version (use `kubectl version`): client (v1.21.6), server (v1.22.8).
- Kubernetes installer & version: kubespray-1.18
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from `/etc/os-release`): CentOS 7.9

**Comment by jenting** [comment]
You need to configure the BackupStoreLocation.

**Comment by jenting** [comment]
Yes, for AWS and MinIO, configure the storage provider as AWS.

**Comment by Philippians413** [comment]
and what about SFTP?

**Comment by jenting** [comment]
> SFTP

Velero supports the object storage server _only_. I remember SFTP isn't an object storage server.
You could check Velero supports plugins for object storage https://velero.io/plugins/.

**Comment by Philippians413** [comment]
@jenting Could we create a backup with csi plugin and save it localy in our k8s pv? Is it possible?

**Comment by jenting** [comment]
> @jenting Could we create a backup with csi plugin and save it localy in our k8s pv? Is it possible?

Yes, the CSI plug-in needs the Kubernetes CSI volume snapshot controller and it's CRDs to achieve backup/restore the PVC.

**Comment by jenting** [comment]
I think this issue is addressed already, I'll close this issue now.
Freel free to reopen it if you have other concerns.
