### ISSUE TITLE
v2.29.7 parse error at (support/charts/velero/templates/servicemonitor.yaml:1)

### ISSUE THREAD

**Issue by traj2073** [vmware-tanzu/helm-charts#379]
**What steps did you take and what happened:**

when i try to upgrade to the latest version ( v2.29.7) getting below error 

**`Error: UPGRADE FAILED: parse error at (support/charts/velero/templates/servicemonitor.yaml:1): unclosed action`**

**What did you expect to happen:**

getting upgrade without any issue

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

 issue seems to be with below code line

`{{- if and
  .Values.metrics.enabled
  .Values.metrics.serviceMonitor.enabled
  (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1")
}}`

**Environment:**

- helm version (use `helm version`):  3.8.0
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): v2.29.7
- Kubernetes version (use `kubectl version`): 1.20.0
- Kubernetes installer & version: 1.20.0
- Cloud provider or hardware configuration: EKS

**Comment by mahfoud-hub** [comment]
did you resolved the issue i had the same problem? can you give the image tag of the previous version please

**Comment by jenting** [comment]
@ariep could you help with this? Thank you.

**Comment by traj2073** [comment]
> did you resolved the issue i had the same problem? can you give the image tag of the previous version please

by downgrading to previous vision resolve the issue, seems issue with the version v2.29.7

**Comment by mahfoud-hub** [comment]
@traj2073 Which version do I need to downgrading to?

**Comment by traj2073** [comment]
> @traj2073 Which version do I need to downgrading to?

[velero-2.29.6](https://github.com/vmware-tanzu/helm-charts/releases/tag/velero-2.29.6) works for me

**Comment by mahfoud-hub** [comment]
@traj2073 thanks i will try it

**Comment by mahfoud-hub** [comment]
@traj2073 hey i have setup the velero chart with this value and i have the exact same message:

```
image:
  repository: velero/velero
  tag: v2.29.6
  pullPolicy: IfNotPresent
```

**Comment by ariep** [comment]
I've tried to reproduce this with a slightly older helm version (3.7.0), but I couldn't reproduce, possibly because I didn't have the right (failing) helm values and/or environment.

@traj2073 (or someone else with this problem) could you please specify, besides what you wrote in the issue description (helm 3.8.0, etc.), also
* the helm values used when installing (please remove sensitive information if necessary); and
* whether your cluster has the relevant monitoring APIs (e.g., output of `kubectl api-resources | grep monitoring`).

**Comment by traj2073** [comment]
@ariep  fyi

- no output for kubectl api-resources | grep monitoring

- main values.yaml
`velero:
  ## adding pod priorityClassName ##
  priorityClassName: support-high-priority
  configuration:
    provider: aws
    backupStorageLocation:
      name: default
      provider: aws
      bucket: 'set in values'
      config:
        region: us-east-1
        kmsKeyId: 'set in values'     #use the relevant KMS Id for the required bucket 
    volumeSnapshotLocation:
      name: aws
      provider: aws
      config:
        region: us-east-1
    logLevel: info

  # Init containers to add to the Velero deployment's pod spec. At least one plugin provider image is required
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.3.0
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins
  podAnnotations:
    iam.amazonaws.com/role: 'set in values' #worker node role
  
  kubectl:
    image:
      repository: docker.io/bitnami/kubectl

  # Info about the secret to be used by the Velero deployment
  credentials:
    useSecret: false

  # Backup schedules to create.
  schedules:
    firstbackup:
      schedule: '0 1 * * *' #7p.m CST
      template:
        ttl: '160h'
        includedNamespaces:
          - system
    secondbackup:
      schedule: '0 11 * * *' #5a.m CST
      template:
        ttl: '160h'
        includedNamespaces:
          - system`

- support values.yaml
`velero:
  image:
    imagePullSecrets:
      - dockerhub-cred
  configuration:
    backupStorageLocation:
      bucket: <BUCKET NAME>
      config:
        kmsKeyId: <KMS ID>
  podAnnotations:
    iam.amazonaws.com/role: <ROLE NAME>`
