### ISSUE TITLE
i can't install the velero helm chart  (Error: parse error at (velero/templates/servicemonitor.yaml:1): unclosed action)

### ISSUE THREAD

**Issue by mahfoud-hub** [vmware-tanzu/helm-charts#380]
**What steps did you take and what happened:**
When i try to install the helm chart i'm getting below error

Error: UPGRADE FAILED: parse error at (support/charts/velero/templates/servicemonitor.yaml:1): unclosed action

**What did you expect to happen:**

install the velero without any issue

the problem seems to come from

{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Comment by jenting** [comment]
Duplicate to #379, close it.
