### ISSUE TITLE
ServiceMonitor Not Deploying

### ISSUE THREAD

**Issue by B1ue-W01f** [vmware-tanzu/helm-charts#388]
**What steps did you take and what happened:**
Deployed helm chart utilising argocd kustomize+helm with correct values:

    metrics:
      enabled: true
      scrapeInterval: 30s
      scrapeTimeout: 10s
    
      # service metdata if metrics are enabled
      service:
        annotations: {}
        labels: {}
    
      # Pod annotations for Prometheus
      podAnnotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8085"
        prometheus.io/path: "/metrics"
    
      serviceMonitor:
        enabled: true
        additionalLabels: {}
        # ServiceMonitor namespace. Default to Velero namespace.
        namespace: velero

**What did you expect to happen:**
ServiceMonitor resource should be deployed however none is including when building manually.

**Anything else you would like to add:**
I suspect the issue is to do with the well-meaning capabilities check added 3 months ago to the ServiceMonitor template
`{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled (.Capabilities.APIVersions.Has "monitoring.coreos.com/v1") }}`

I'd argue, particularly with the default having service monitor disabled, we realistically should be able to expect someone deploying the chart with it intentionally enabled to know if prometheus CRDs are already deployed, and to know how to resolve if they're not.

As a result and with incompatibility with common CI clients as well as manual builds, I believe this check should be removed.

**Comment by reefland** [comment]
Bumping into this now as well.  No service Monitor with ArgoCD deployed Velero.

**Comment by jenting** [comment]
> Deployed Chart `3.1.2`, these in my `values.yaml`:
> 
> ```
>       metrics:
>         enabled: true
>         scrapeInterval: 30s
>         scrapeTimeout: 10s
> 
>       service:
>         annotations: {}
>         labels: {}
> 
>       serviceMonitor:
>         enabled: true
>         autodetect: false
>         annotations: {}
>         additionalLabels: {}
>         namespace: velero
> 
>       prometheusRule:
>         enabled: true
>         additionalLabels: {}
>         namespace: velero
>         # Rules to be deployed
>         spec:
>           - alert: VeleroBackupPartialFailures
>             annotations:
>               message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} partialy failed backups.
>             expr: |-
>               velero_backup_partial_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
>             for: 15m
>             labels:
>               severity: warning
>           - alert: VeleroBackupFailures
>             annotations:
>               message: Velero backup {{ $labels.schedule }} has {{ $value | humanizePercentage }} failed backups.
>             expr: |-
>               velero_backup_failure_total{schedule!=""} / velero_backup_attempt_total{schedule!=""} > 0.25
>             for: 15m
>             labels:
>               severity: warning
> ```
> 
> Not seeing a serviceMonitor for Velero:
> 
> ```
> $ k get servicemonitor -A
> NAMESPACE    NAME                                 AGE
> gitea        gitea                                26d
> monitoring   argocd-application-controller        228d
> monitoring   argocd-applicationset-controller     228d
> monitoring   argocd-notifications-controller      228d
> monitoring   argocd-redis                         228d
> monitoring   argocd-repo-server                   228d
> monitoring   argocd-server                        228d
> monitoring   grafana                              189d
> monitoring   kube-state-metrics                   189d
> monitoring   mosquitto-exporter-metrics           225d
> monitoring   node-exporter                        189d
> monitoring   prometheus-alertmanager              189d
> monitoring   prometheus-apiserver                 189d
> monitoring   prometheus-coredns                   189d
> monitoring   prometheus-kube-controller-manager   189d
> monitoring   prometheus-kube-etcd                 189d
> monitoring   prometheus-kube-proxy                189d
> monitoring   prometheus-kube-scheduler            189d
> monitoring   prometheus-kubelet                   189d
> monitoring   prometheus-operator                  189d
> monitoring   prometheus-prometheus                189d
> rook-ceph    rook-ceph-mgr                        77d
> ```
> 
> Not seeing any Prometheus Rules being created either:
> 
> ```
> $ k get prometheusrules -A
> NAMESPACE    NAME                                              AGE
> monitoring   argocd-app-sync-alerts                            225d
> monitoring   cert-manager-alerts                               214d
> monitoring   minio-truenas-alerts                              7d23h
> monitoring   mosquitto-alerts                                  167d
> monitoring   node-alerts                                       225d
> monitoring   node-zfs-alerts                                   180d
> monitoring   pod-alerts                                        166d
> monitoring   prometheus-alertmanager.rules                     189d
> monitoring   prometheus-alerts                                 190d
> monitoring   prometheus-config-reloaders                       189d
> monitoring   prometheus-etcd                                   189d
> monitoring   prometheus-general.rules                          189d
> monitoring   prometheus-k8s.rules                              189d
> monitoring   prometheus-kube-apiserver-availability.rules      189d
> monitoring   prometheus-kube-apiserver-burnrate.rules          189d
> monitoring   prometheus-kube-apiserver-histogram.rules         189d
> monitoring   prometheus-kube-apiserver-slos                    189d
> monitoring   prometheus-kube-prometheus-general.rules          189d
> monitoring   prometheus-kube-prometheus-node-recording.rules   189d
> monitoring   prometheus-kube-scheduler.rules                   189d
> monitoring   prometheus-kube-state-metrics                     189d
> monitoring   prometheus-kubelet.rules                          189d
> monitoring   prometheus-kubernetes-apps                        189d
> monitoring   prometheus-kubernetes-resources                   189d
> monitoring   prometheus-kubernetes-storage                     189d
> monitoring   prometheus-kubernetes-system                      189d
> monitoring   prometheus-kubernetes-system-apiserver            189d
> monitoring   prometheus-kubernetes-system-controller-manager   189d
> monitoring   prometheus-kubernetes-system-kube-proxy           189d
> monitoring   prometheus-kubernetes-system-kubelet              189d
> monitoring   prometheus-kubernetes-system-scheduler            189d
> monitoring   prometheus-node-exporter                          189d
> monitoring   prometheus-node-exporter.rules                    189d
> monitoring   prometheus-node-network                           189d
> monitoring   prometheus-node.rules                             189d
> monitoring   prometheus-prometheus                             189d
> monitoring   prometheus-prometheus-operator                    189d
> monitoring   sealed-secrets-alerts                             205d
> monitoring   traefik-alerts                                    225d
> rook-ceph    prometheus-ceph-rules                             77d
> ```

@tholander Could you please help above?

**Comment by reefland** [comment]
Fixed...  `service`, `serviceMonitor` and `prometheusRule` needed to be bumped under `metrics`.  Working as expected now.
