### ISSUE TITLE
Add csiSnapshotTimeout option for v1.9.1

### ISSUE THREAD

**Issue by drewboswell** [vmware-tanzu/helm-charts#393]
**Describe the problem/challenge you have**
add csiSnapshotTimeout to CRDs as defined in https://github.com/vmware-tanzu/velero/pull/5189/files, which released with v1.9.1.

**Comment by jenting** [comment]
[Velero helm chart 2.31.3](https://github.com/vmware-tanzu/helm-charts/releases/tag/velero-2.31.3) released, closing it.

**Comment by drewboswell** [comment]
um. wow. seriously the reactivity +++ 

Thank you.
