### ISSUE TITLE
The readme link to Velero CLI does not work

### ISSUE THREAD

**Issue by easyenglishcoding** [vmware-tanzu/helm-charts#42]
Hi!

Please correct link to Velero CLI in README.md

Regards
Radek

![error](https://user-images.githubusercontent.com/59885921/72686646-3f351d00-3af7-11ea-9531-a8d394f892ef.jpg)

**Comment by cpanato** [comment]
Thanks for letting bus know, are you willing to open a PR to fix this issue? Otherwise I can fix that tomorrow.

**Comment by carlisia** [comment]
Maybe this was fixed, but it works now: https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero#installing-the-velero-cli.

Thanks for reporting it, @easyenglishcoding!
