### ISSUE TITLE
Provide support to be able to create velero objects(schedule/backup etc) from any namespace and velero server in another namespace

### ISSUE THREAD

**Issue by Falcondevils** [vmware-tanzu/helm-charts#426]
Let's say I deployed velero server in velero namespace. I should be able to create other velero objects like backup/schedule/backupstoragelocation/etc in a different namespace. Velero should still be able to read those objects and take actions accordingly.

It's more like how external secrets operator works.

**Comment by sseago** [comment]
If we were to do this, it would have to be a non-default option. Currently if Velero is installed in two different namespaces, each namepace's velero only responds to its own CRs. If velero normally looked in all namespaces, then two different velero instances would be competing for the same resources.

**Comment by sseago** [comment]
Also, this isn't a helm charts issue -- helm-charts is just a means to install Velero. Velero itself would need to be modified to enable this as a (non-default) option.

**Comment by Falcondevils** [comment]
> Also, this isn't a helm charts issue -- helm-charts is just a means to install Velero. Velero itself would need to be modified to enable this as a (non-default) option.

Agree not helm chart issue and Velero issue

**Comment by Falcondevils** [comment]
I see similar issues in Velero for this and it's not a helm chart issue.  https://github.com/vmware-tanzu/velero/issues/18
So closing this

**Comment by Falcondevils** [comment]
Can someone delete this issue from here? I don't want to make a mess here. Thanks
