### ISSUE TITLE
List charts on artifacthub.io

### ISSUE THREAD

**Issue by jcpunk** [vmware-tanzu/helm-charts#427]
**Describe the problem/challenge you have**
Finding the official helm charts.

**Describe the solution you'd like**
I tend to use artifacthub as my starting point for finding helm charts. Having this posted there should help increase the visibility of this project.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by sdelrio** [comment]
I think is already there:

https://artifacthub.io/packages/helm/vmware-tanzu/velero
