### ISSUE TITLE
Velero creates volumesnapshots even if snapshotsEnabled feature disabled.

### ISSUE THREAD

**Issue by Subetov** [vmware-tanzu/helm-charts#435]
**What steps did you take and what happened:**
- I have installed Velero Helm Chart with 'snapshotsEnabled: false'
  (Whether to create volumesnapshotlocation crd, if false => disable snapshot feature)
- backup created
  (I supposed backup will be created only with Restic, but the volumesnapshot is also created)
Then I can't restore the backup from Restic, because Velero tries to restore from snapshot.

**What did you expect to happen:**
Velero doesn't create volumesnapshots CustomResource if 'snapshotsEnabled: false'

**Anything else you would like to add:**
Seems it will create volumesnapshots while velero.io/csi-volumesnapshot-class: "true" label is present in VolumeSnapshotClass

Could you tell me  please how to deploy a Helm Chart with fs-backup support, but without volumesnapshots.
Can't manage to take fs backup with Restic (if volumesnapshots disables \ no  velero.io/csi-volumesnapshot-class label)

```
level=error msg="Error backing up item" backup=velero/test-minio-restic-fs-backup error="error executing custom action (groupResource=persistentvolumeclaims, namespace=ice-minio, name=minio-pvc): rpc error: code = Unknown desc = failed to get volumesnapshotclass for storageclass openebs-zfspv: failed to get volumesnapshotclass for provisioner zfs.csi.openebs.io, ensure that the desired volumesnapshot class has the velero.io/csi-volumesnapshot-class label" logSource="pkg/backup/backup.go:425" name=minio-6895586d54-swng8
```

If label added then it creates 'podvolumebackups.velero.io' and data backup is created via Restic, but it also creates a volumesnapshots.snapshot.storage.k8s.io.

**Environment:**

- helm version (use `helm version`): v3.10.3
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): velero-3.1.2
- Kubernetes version (use `kubectl version`): v1.24.8

**Comment by Subetov** [comment]
**UPD**
It seems that the key "--default-volumes-to-fs-backup" does not work.
If the "velero-plugin-for-csi" plugin is installed then the snapshot will be taken anyway.
It is also not possible to specify which method to use for restoring the data (Snapshot or Restik, etc)

**Comment by jenting** [comment]
@qiuming-best could you help with this issue when you are available?

**Comment by qiuming-best** [comment]
@Subetov Have you ever tried the command `velero backup create xxx --default-volumes-to-fs-backup --snapshot-volumes=false`?

**Comment by Ulrar** [comment]
I seem to have the same issue, the CRD is there regardless.
When manually creating a backup with `--snapshot-volumes=false` it does get disabled, but when using a schedule with `snapshotVolumes: false` the resulting backup has in on `auto` for some reason, and tries to take one
