### ISSUE TITLE
[velero] install from helm chart works, but no pods show up?

### ISSUE THREAD

**Issue by dirtbag** [vmware-tanzu/helm-charts#45]
**What steps did you take and what happened:**
I installed a velero from terraform to my gke cluster and it looks like the chart installed successfully, but there are no velero pods running and there are no deployments that I can find.

**What did you expect to happen:**
I expected at least a velero pod somewhere on my cluster.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
Error from server (NotFound): deployments.extensions "velero" not found

**Anything else you would like to add:**
client: v2.13.1   server: v2.15.1 on google GKE 

**Environment:**
google GKE

- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", -
- kubectl version:
GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"archive", BuildDate:"2019-08-15T00:00:00Z", GoVersion:"go1.13beta1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-gke.13", GitCommit:"39fe6cf6b77a3a0f620bd89db92f5133be67aa91", GitTreeState:"clean", BuildDate:"2019-11-13T20:44:51Z", GoVersion:"go1.12.11b4", Compiler:"gc", Platform:"linux/amd64"}
```
helm info:
```
NAME                    	REVISION	UPDATED                 	STATUS  	CHART                     	
velero                  	1       	Fri Dec 20 14:53:39 2019	DEPLOYED	velero-2.3.2              	1.1.0      	velero      
```
```
helm status velero
LAST DEPLOYED: Fri Dec 20 14:53:39 2019
NAMESPACE: velero
STATUS: DEPLOYED

RESOURCES:
==> v1/BackupStorageLocation
NAME     AGE
default  134m

==> v1/ClusterRoleBinding
NAME           AGE
velero-server  134m

==> v1/Secret
NAME    TYPE    DATA  AGE
velero  Opaque  0     134m

==> v1/ServiceAccount
NAME           SECRETS  AGE
velero-server  1        134m

==> v1/VolumeSnapshotLocation
NAME     AGE
default  134m


NOTES:
Check that the velero is up and running:

    kubectl get deployment/velero -n velero

Check that the secret has been created:

    kubectl get secret/velero -n velero

Once velero server is up and running you need the client before you can use it
1. wget https://github.com/vmware-tanzu/velero/releases/download/v1.1.0/velero-v1.1.0-darwin-amd64.tar.gz
2. tar -xvf velero-v1.1.0-darwin-amd64.tar.gz -C velero-client

More info on the official site: https://github.com/vmware-tanzu/velero#install-client
```

```
$ kubectl get deployment/velero -n velero
Error from server (NotFound): deployments.extensions "velero" not found
```
what other logs can I look at to troubleshoot this?

-db

**Comment by dirtbag** [comment]
we actually got it working.. Ill have to see If I can post what finally worked for us later.
stay tuned.  ;)

**Comment by carlisia** [comment]
Hey @dirtbag ping, we can't handle the suspense any longer! lol

**Comment by dirtbag** [comment]
ooh man.. sorry, totally forgot about this..   heres the values file I ended up with .. 
looks like we ended up using an existing secret.. 

initContainers:
  - name: gcp
    image: velero/velero-plugin-for-gcp:v1.0.0
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /target
        name: plugins

rbac:
  create: true

metrics:
  enabled: true
  scrapeInterval: 30s


serviceAccount:
  server:
    create: true

snapshotsEnabled: true

credentials:
  # Whether a secret should be used as the source of IAM account
  # credentials. Set to false if, for example, using kube2iam or
  # kiam to provide IAM credentials for the Velero pod.
  useSecret: true
  # Name of a pre-existing secret (if any) in the Velero namespace
  # that should be used to get IAM account credentials. Optional.
  # existingSecret:
  # Data to be stored in the Velero secret, if `useSecret` is
  # true and `existingSecret` is empty. This should be the contents
  # of your IAM credentials file.
  existingSecret: velero-service

configuration:
  provider: gcp
  backupStorageLocation:
    name: gcp

**Comment by jenting** [comment]
Hi @dirtbag, from the discussion thread I believe the issue got fixed already, close this issue.

**Comment by jenting** [comment]
@YoucefGuichi Did you install/upgrade to velero chart version `4.0.0`? If yes, you encountered this issue #454.
