### ISSUE TITLE
Version 4.0.0 is not useable 

### ISSUE THREAD

**Issue by Ujkugri** [vmware-tanzu/helm-charts#454]
**What steps did you take and what happened:**
When updating to helmchart version 4.0.0, the deployment of the velero server will be deleted. Here is a part of the output of my `helmfile diff`:

```
XXX-backup, velero, Deployment (apps) has been removed:
- # Source: velero/templates/deployment.yaml
- apiVersion: apps/v1
- kind: Deployment
- metadata:
...
```

**What did you expect to happen:**
That the deployment gets updated.

**Anything else you would like to add:**
This is probably because of https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/deployment.yaml#L1

With the newest version, you removed the key `configuration.provider`. Users will get an information like:
```
  Error: Failed to render chart: exit status 1: Error: execution error at (velero/templates/NOTES.txt:78:4): 
  #################################################################################
  ######   BREAKING: The config values passed contained no longer accepted    #####
  ######             options. See the messages below for more details.        #####
  ######                                                                      #####
  ######             To verify your updated config is accepted, you can use   #####
  ######             the `helm template` command.                             #####
  #################################################################################
  REMOVED: .configuration.provider has been removed, instead each backupStorageLocation and volumeSnapshotLocation has a provider configured
  Use --debug flag to render out invalid YAML
  Error: plugin "diff" exited with error
```
But this key is in your if-condition, so since there is no `configuration.provider`, helm thinks it has to "update" the deployment by deleting it.

**Environment:**
- helm chart version 4.0.0 and app version 1.11.0

**Comment by benedikt-bartscher** [comment]
Same here, see my comment in the related PR: https://github.com/vmware-tanzu/helm-charts/pull/413#issuecomment-1523638626

**Comment by larivierec** [comment]
yep, same here.
velero deployment is completely removed and only agents are running

**Comment by benedikt-bartscher** [comment]
A simple fix is to remove the breaking check in NOTES.txt: https://github.com/vmware-tanzu/helm-charts/blob/4553dc54fb871838e406b07ebe99e5c7a4d8fcb6/charts/velero/templates/NOTES.txt#L37-L39

**Comment by benedikt-bartscher** [comment]
Another indicator that removing the breaking check is probably the correct solution: According to the comments in `values.yaml` `configuration.provider` is still used as a default value.
https://github.com/vmware-tanzu/helm-charts/blob/4553dc54fb871838e406b07ebe99e5c7a4d8fcb6/charts/velero/values.yaml#L242-L243

**Comment by larivierec** [comment]
This depends how the application runs.
If the application supports the use of a Go slice, the helm chart should be doing a for each over all the backup storage locations and using that provider.

If it doesn't, it should be one deployment per storage location. 
Which, to me is kind of weird.
