### ISSUE TITLE
Outdated comment about `configuration.provider`

### ISSUE THREAD

**Issue by jorianvo** [vmware-tanzu/helm-charts#457]
**What steps did you take and what happened:**
I was reading the [values.yaml](https://github.com/vmware-tanzu/helm-charts/blob/e9e8c60ed2e9ca45493670a1b047b7968026d7bf/charts/velero/values.yaml) when preparing to upgrade `Velero` to `v1.11`.
The comment regarding the `backupStorageLocation.provider` and `volumeSnapshotLocation.provider` both [mention](https://github.com/vmware-tanzu/helm-charts/blob/e9e8c60ed2e9ca45493670a1b047b7968026d7bf/charts/velero/values.yaml#L242C1-L243):
```shell
If omitted `configuration.provider` will be used instead.
```

**What did you expect to happen:**
My current configuration which uses the `configuration.provider` to still work after upgrading to `v1.11`.
However I received the following error message:
```
REMOVED: .configuration.provider has been removed, instead each backupStorageLocation and volumeSnapshotLocation has a provider configured
```

Which makes sense looking at [this](https://github.com/vmware-tanzu/helm-charts/commit/4553dc54fb871838e406b07ebe99e5c7a4d8fcb6) commit.

So a very simple fix, just to help avoid some confusion. Please let me know if you want me to create a PR.

**Comment by jenting** [comment]
@jorianvo 
Thank you for creating this issue. We deprecated the `configuration.provider` from helm chart version `4.0.0`.
If you like, could you help make a PR to update the comment for `configuration.provider`?
