### ISSUE TITLE
Velero helm apply schedule disabled flag does nothing 

### ISSUE THREAD

**Issue by kub3let** [vmware-tanzu/helm-charts#462]
**What steps did you take and what happened:**
If you deploy schedules via helm and after that change the `disabled` flag to `true` the apply does not update the schedule state.

Overall the `disabled` flag currently only prevents schedules from being created, but otherwise does nothing.

**What did you expect to happen:**

If `disabled` is changed to `true` on a helm apply the schedule status should change to `Disabled`

**Anything else you would like to add:**

This was already mentioned in https://github.com/vmware-tanzu/helm-charts/issues/392 by @Spots87 as well, I just created a dedicated issue for it since I'm affected by this as well.

**Environment:**

- helm version (use `helm version`): v3.12.0
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): velero-4.0.3 / 1.11.0
- Kubernetes version (use `kubectl version`): v1.27.2+k3s1
- Kubernetes installer & version: k3s v1.27.2
- Cloud provider or hardware configuration: on-premise, KVM testlab
- OS (e.g. from `/etc/os-release`): Debian 11 / Kernel 5.10.179

**Comment by bsteinm2** [comment]
@jenting Just now having a look at this bug... not sure what the best implementation of this fix would be... Would there need to be a 'disabled' phase added to the status field of the schedule CRD? Right now I don't see a phase that reflects this [in the CRD here](https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/crds/schedules.yaml#L534).

**Comment by jenting** [comment]
@bsteinm2 
I created a PR to address it.
Would you mind to help me verify it? Appreciate 🙏

**Comment by kub3let** [comment]
@jenting I tested your PR and technically it works.

The disabled flag is now used but the schedule is completely deleted, I would have more expected it to be still listed with `Status` `Disabled` but either way is fine I guess ?

```
(run helm apply via ansible to create schedule with disabled false)

❯ v get schedule
NAME                  STATUS    CREATED                         SCHEDULE    BACKUP TTL   LAST BACKUP   SELECTOR   PAUSED
velero-daily-test     Enabled   2023-08-14 17:28:34 +0000 UTC   0 2 * * *   240h0m0s     n/a           <none>     false

(run helm apply via ansible with disabled true)

❯ v get schedule

(no output schedule is gone)
```

**Comment by jenting** [comment]
@kub3let The Velero does not support disable schedule right now.
