### ISSUE TITLE
Resource reqeusts and resource limits should not be set by default

### ISSUE THREAD

**Issue by mdnix** [vmware-tanzu/helm-charts#469]
**Describe the problem/challenge you have**
Resource reqeusts and resource limits should not be set by default.

**Describe the solution you'd like**
I recommend leaving the resources block in the values section blank and avoiding any assumptions regarding requests and limits. Since each environment is unique, it is best to provide users with full control and flexibility without making any assumptions.

I'm suggesting this because it's usually the way things are done with most charts. I had a problem where Velero backups kept failing because they were running out of memory. I should have checked the default settings of the chart, but I thought nothing would be activated unless I specifically set it.

**Comment by zaggash** [comment]
I agree.
The commit https://github.com/vmware-tanzu/helm-charts/commit/90450f6ea3448f987f6bb8e5d13491182718f755 is broken and is not working if you have metrics disabled !
