### ISSUE TITLE
Liveness and Readiness Probe PR is broken.

### ISSUE THREAD

**Issue by zaggash** [vmware-tanzu/helm-charts#470]
**What steps did you take and what happened:**
Updating the Charts in place and the application failed to start.

The PR  https://github.com/vmware-tanzu/helm-charts/commit/90450f6ea3448f987f6bb8e5d13491182718f755 assume you have metrics enabled.

**What did you expect to happen:**

The update should run but not affect my workload.

**The output of the following commands will help us better understand what's going on**:
My pod is starting but failling because of :
```
Messages
• Readiness probe errored: strconv.Atoi: parsing "http-monitoring": invalid syntax
````

**Anything else you would like to add:**
The probe uses the metrics endpoint.
However if you have metrics disabled, the liveness config is not valid.

**Environment:**

- helm version (use `helm version`): 3.12.0
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 4.1.0
- Kubernetes version (use `kubectl version`): 1.27.2
- Kubernetes installer & version: k3s 1.27.2+k3s1
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): FlatCar 3374.2.1

**Comment by jenting** [comment]
@maxime1907 could you please help address this issue?

**Comment by sjoukedv** [comment]
The new default probe is only valid if you have `metrics.enabled` (see https://github.com/vmware-tanzu/helm-charts/blob/main/charts/velero/templates/deployment.yaml#L70-74).

#470 solves the issue I am having, but in the ideal world we would automatically set the liveness/readiness probe on the container for those that do have metric enabled

**Comment by zaggash** [comment]
You mean #471 not this issue [#470](https://github.com/vmware-tanzu/helm-charts/issues/470)

right ?

**Comment by sjoukedv** [comment]
Yes, my bad. That's also the one where this issue was referenced.
