### ISSUE TITLE
Have A CI task to verify the CRD folder in sync

### ISSUE THREAD

**Issue by jenting** [vmware-tanzu/helm-charts#480]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

Currently, the CI does not check the CRD folder YAML manifests are synced with the Velero image.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Have a CI task to verify the CRD folder YAML manifests are synced with the Velero image.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by tungbq** [comment]
Hello, may I know the step verify the CRD folder YAML manifests are synced with the Velero image manually?

**Comment by jenting** [comment]
@tungbq 
Compare the YAML between
`velero install --crds-only --dry-run -o yaml` and [crds](https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero/crds) folder.

**Comment by tungbq** [comment]
> @tungbq Compare the YAML between `velero install --crds-only --dry-run -o yaml` and [crds](https://github.com/vmware-tanzu/helm-charts/tree/main/charts/velero/crds) folder.

I'm thinking about the approach to create 2 yaml output files:
- velero install --crds-only --dry-run -o yaml > debug_velero.yml
- kubectl apply --dry-run=client -f crds/ -o yaml > debug_origin.yaml

Then we compare the `debug_velero.yml` with `debug_origin.yaml` to see if they are synced.
Not sure it the right approach, could you please advise and correct if I was wrong? Thanks

**Comment by jenting** [comment]
Sounds good.

Be aware that the YAML output ordering and some extra labels or annotations added from the Velero CLI output.
Essentially, the Velero helm chart labels and annotations should be the same as Velero CLI output.

**Comment by tungbq** [comment]
> @tungbq Sounds good.
> 
> Be aware that the YAML output ordering and some extra labels or annotations added/removed from the Velero CLI output. Essentially, the Velero helm chart labels and annotations should be the same as Velero CLI output. but I am not 100% sure if fully the same or not right now.

As I observed, the diff part mostly is:
```
    status:
      acceptedNames:
        kind: ''
        plural: ''
      conditions: []
      storedVersions: []
```
and
```
kubectl.kubernetes.io/last-applied-configuration: >
    SOME_EXTRA_METADATA...
```

![image](https://github.com/vmware-tanzu/helm-charts/assets/85242618/95888374-706c-4520-91de-64db81be149c)

Trying to find a way to automate this. Not quite simple than I thought.
If you have any advice, please let me know. Thanks!

**Comment by jenting** [comment]
I'd suggest not using kubectl --dry-run=client to generate the CRDs YAML.
Instead, tried to find a way to aggregate the CRDs YAML into one file with the same ordering as `velero install --crds-only --dry-run -o yaml`.

**Comment by jenting** [comment]
Or as an alternative, you could compare the two results.

```console
velero install --crds-only --dry-run -o yaml | kubectl apply --dry-run=client -f - -oyaml > debug_velero.yml
kubectl apply --dry-run=client -f crds/ -o yaml > debug_origin.yaml
```

**Comment by tungbq** [comment]
Thanks @jenting. I'm implementing the workflow upon your suggestion!
