### ISSUE TITLE
Enable image digest option for plugin image

### ISSUE THREAD

**Issue by ranjith-vatakkeel** [vmware-tanzu/helm-charts#492]
**Describe the problem/challenge you have**
Currently, the image `digest` option is not there for the plugin image.

**Describe the solution you'd like**
Include the `digest` field in the helm templates.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by jenting** [comment]
@ranjith-vatakkeel The plugin image directly render from the values.yaml https://github.com/vmware-tanzu/helm-charts/blob/2432de2a2d866907be9bba09e295f8a36746fcce/charts/velero/templates/deployment.yaml#L232-L239

So, change the plugin image tag to digest should work.
