### ISSUE TITLE
Add new Velero Charts repository to the Helm Hub

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/helm-charts#5]
From @cpanato:
> Add new Velero Charts repository to the Helm Hub. See https://github.com/helm/hub#how-to-add-your-helm-charts

**Comment by carlisia** [comment]
let's keep this issue to just moving the existing Velero chart. 

Updating for Helm 3 compatibility is being tracked here: https://github.com/vmware-tanzu/helm-charts/issues/7

**Comment by carlisia** [comment]
This is a dup of https://github.com/vmware-tanzu/helm-charts/issues/3, which is done, so closing this.

**Comment by carlisia** [comment]
Nope, it is not a dup, this is about Helm Hub. Reopening.

**Comment by cpanato** [comment]
PR: https://github.com/helm/hub/pull/214

**Comment by carlisia** [comment]
Dnoe: https://github.com/helm/hub/pull/214
