### ISSUE TITLE
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: BackupStorageLocation 

### ISSUE THREAD

**Issue by jonathanparedes-nzta** [vmware-tanzu/helm-charts#500]
**What steps did you take and what happened:**
We are trying to upgrade helm chart version from 3.1.4 to 5.0.2

helm upgrade velero-azure --version 5.0.2  vmware-tanzu/velero --namespace velero --create-namespace --dry-run --debug --set installCRDs=true

**What did you expect to happen:**
Velero gets updated deployed correctly.

**The output of the following commands will help us better understand what's going on**:
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: BackupStorageLocation "default" in namespace "velero" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "velero-azure"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "velero"

**Anything else you would like to add:**
Please advise on how to fix the encountered issue. 

**Environment:**

- helm version (use `helm version`): v3.1.0
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): velero-3.1.4
- Kubernetes version (use `kubectl version`): v1.25.6

**Comment by sedflix** [comment]
I think this is due to https://github.com/vmware-tanzu/helm-charts/pull/490

**Comment by jonathanparedes-nzta** [comment]
> I think this is due to #490

Thanks for pointing me to the right direction. I was able to upgrade helm chart by deleting BSL crd and installing the latest
