### ISSUE TITLE
No way to enable --default-snapshot-move-data

### ISSUE THREAD

**Issue by efbicief** [vmware-tanzu/helm-charts#516]
**Describe the problem/challenge you have**
In Velero 1.12.1, the `--default-snapshot-move-data` flag was added to velero install. There is currently no way to specify this flag via the Helm chart.

**Describe the solution you'd like**
A Helm value to enable this flag. This would need to be templated in to the deployment container args list [here](https://github.com/vmware-tanzu/helm-charts/blob/ef6072a9ae97aba647948961cee9879ad837383c/charts/velero/templates/deployment.yaml#L82C11-L82C12).

**Anything else you would like to add:**
N/A

**Environment:**

- helm version (use `helm version`): 3.12.1
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): 5.1.3
- Kubernetes version (use `kubectl version`): 1.27.3
- Kubernetes installer & version: 1.28.0 kubeadm

**Comment by jenting** [comment]
It probably because it's a new flag and we missed it.
Perhaps you could file a PR to address it, appreciate.
