### ISSUE TITLE
`velero-upgrade-crds` job is stuck at `Init:ImagePullBackOff` because `kubectl` image is not up-to-date.

### ISSUE THREAD

**Issue by reitermarkus** [vmware-tanzu/helm-charts#531]
**What steps did you take and what happened:**

Installing velero on a new 1.29 cluster.

**What did you expect to happen:**

Deployment to succeed, without needing to manually specify an older `kubectl` image.

**The output of the following commands will help us better understand what's going on**:

N/A

**Anything else you would like to add:**

Don't depend on a `kubectl` image which is still not updated 6 days after a Kubernetes release.

**Environment:**

- helm version (use `helm version`): v3.13.3
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`): velero-5.2.0	1.12.2
- Kubernetes version (use `kubectl version`): v1.29.0
- Kubernetes installer & version:
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from `/etc/os-release`):  Talos 1.6.0

**Comment by jenting** [comment]
I see the [bitnami/kubectl:1.29.0](https://hub.docker.com/layers/bitnami/kubectl/1.29.0/images/sha256-128874c55e9aa7866511c74ce1de123cc1ef73c0e4d073d977a15f6e1dda73eb?context=explore) kubectl image is available.
Is this issue still present?

**Comment by reitermarkus** [comment]
> Is this issue still present?

Obviously it's not present now that the newest version is available, but it will break again when Kubernetes 1.30 is released and `bitnami/kubectl:1.30.0` takes a month to be released.

**Comment by jenting** [comment]
We will add more CI test once the newer Kubernetes minor versions released.
