### ISSUE TITLE
Kubernetes 1.28 compatibility and velero 1.13 integration

### ISSUE THREAD

**Issue by fabMrc** [vmware-tanzu/helm-charts#540]
Hello

Currently the last 22.2 helm chart version embeds 1.12 Velero release and it is not compatible with kubernetes 1.28.x 
I did not test to override the appVersion in the Helm chart maybe it works but do you have some visibility for next release about a 1.28.x compatibility ?

thanks a lot

**Comment by jenting** [comment]
Helm chart with velero 1.13 released, related to [PR](https://github.com/vmware-tanzu/helm-charts/pull/535).
