### ISSUE TITLE
velero server flag for default item operation timeout

### ISSUE THREAD

**Issue by DreamingRaven** [vmware-tanzu/helm-charts#545]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]

Currently, whenever I back up some large volume like Nextcloud, the backup invariably times out, as the default item operation timeout is 4h. In the current helm chart there is no way to modify this default, which has AFAIK existed since https://github.com/vmware-tanzu/velero/commit/2aaa85bc5830ef9ef8b81be5db6eae6fa310056b. Technically you can work around this by specifically defining a backup with a specific item-operation-timeout time, however this does not work for schedules since there is no apparent way to modify this given the current CRDs for backup-storage-location, volume-snapshot-location or schedule.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

This can be as simple as adding one more to the existing plethora of overrides: https://github.com/vmware-tanzu/helm-charts/blob/01ae2d9d6b72989172cda63a289bc3e291178c7b/charts/velero/templates/deployment.yaml#L86-L155

And adding a line to the appropriate configuration section:
https://github.com/vmware-tanzu/helm-charts/blob/01ae2d9d6b72989172cda63a289bc3e291178c7b/charts/velero/values.yaml#L389-L449

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

While it is not necessary for this specific feature I note that the current setup is incredibly verbose, is there no way to define an arbitrary set of options to the server as a list? Or is there some application specific reason it was templated in this way?

**Environment:**

environment agnostic as of 5.3.0 is simply not templated

**Comment by DreamingRaven** [comment]
Hey, just a ping to keep things alive, especially for the PR.

**Comment by jenting** [comment]
Thanks for the issue and PR.
