### ISSUE TITLE
Possibility to edit timestamp format on scheduled backup

### ISSUE THREAD

**Issue by WRKT** [vmware-tanzu/helm-charts#566]
**Describe the problem/challenge you have**
I am trying to implement a scheduled backup using Velero daily, so in the default `<TIMESTAMP>` format `YYYYMMDDHHMMSS`, I would like to be able to remove the `HHMMSS`. 

**Describe the solution you'd like**
As example, the final format I want is `backup-20240411` but not `backup-20240411125400`, so I would like to have the possibility to edit the timestamp format for my scheduled velero backup.

**Environment:**

- helm version: v3.14.3
- helm chart version: v6.0.0
- velero version: v1.13.0
- Kubernetes version: v1.29
- Kubernetes installer & version: kind cluster
- OS: Debian bookworm

**Comment by qiuming-best** [comment]
Sorry, I do not support it

**Comment by WRKT** [comment]
Should I submit my ask to the velero repository directly ?

**Comment by jenting** [comment]
Yes, please file a feature request issue to the velero repo, thanks.

**Comment by WRKT** [comment]
OK i will do it. Closing the issue.
