### ISSUE TITLE
Upgrade to Velero v1.14.0

### ISSUE THREAD

**Issue by NoamGaloz1** [vmware-tanzu/helm-charts#592]
**Describe the problem/challenge you have**
[A description of the current limitation/problem/challenge that you are experiencing.]
My vulnerabilities scans are failing because velero v1.13.2 uses golang run-time outdated version.

**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Velero has been realesed a version (v1.14.0) with updated golang-runtime version, please use new velero version.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- helm version (use `helm version`): 
- helm chart version and app version (use `helm list -n <YOUR NAMESPACE>`):
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by amareshgreat** [comment]
Velero 1.14 is released but helm chart for velero 1.14.x is not yet released. 
when the helm-chart for velero 1.14.x will be released?

**Comment by NoamGaloz1** [comment]
> Velero 1.14 is released but helm chart for velero 1.14.x is not yet released. when the helm-chart for velero 1.14.x will be released?

There is an almost ready PR for it, I guess it is pending for another reviewer 
https://github.com/vmware-tanzu/helm-charts/pull/590
