### ISSUE TITLE
Deprecate the helm/charts Velero chart

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/helm-charts#6]
From @cpanato:
> Deprecate the stable/velero chart in helm/charts. See https://github.com/helm/charts/blob/master/PROCESSES.md#deprecating-a-chart

**Comment by cpanato** [comment]
will do it tomorrow

**Comment by cpanato** [comment]
PR in helm chart here: https://github.com/helm/charts/pull/19719

**Comment by carlisia** [comment]
PR merged.
