### ISSUE TITLE
Update Velero Helm chart for compatibility with Helm 3

### ISSUE THREAD

**Issue by carlisia** [vmware-tanzu/helm-charts#7]
Please see the original issue reported by @joschi36: 

https://github.com/helm/charts/issues/19387

**Comment by carlisia** [comment]
Blocked by: https://github.com/vmware-tanzu/helm-charts/issues/2

**Comment by carlisia** [comment]
No longer blocked.

**Comment by wesmiles** [comment]
Hi, Is there a view to how long it will take to support Helm 3? Thanks

**Comment by carlisia** [comment]
@cpanato would you have the bandwidth to tackle this in the near future?

**Comment by cpanato** [comment]
yes @carlisia

**Comment by marvinf95** [comment]
Is there any update about this issue? :)

**Comment by branttaylor** [comment]
@cpanato @carlisia is there any estimate when Velero might support Helm v3? I know several other people have asked, but there has been no response so far.

**Comment by vitobotta** [comment]
Hi @carlisia does the helm chart still support helm 2 only? Thanks

**Comment by carlisia** [comment]
Hey @branttaylor, @wesmiles and @vitobotta, a PR review for this is wip: https://github.com/vmware-tanzu/helm-charts/pull/81

**Comment by vitobotta** [comment]
Thanks @carlisia , hopefully it will be merged soon.
