### ISSUE TITLE
Create new branch called `gh-pages`

### ISSUE THREAD

**Issue by cpanato** [vmware-tanzu/helm-charts#9]
- To host the chart releases.
- Also need to configure Github pages and point to this branch
- maybe set a dns

cc @carlisia 

This closes https://github.com/vmware-tanzu/helm-charts/issues/5.

**Comment by carlisia** [comment]
`gh-pages` has been created.

**Comment by carlisia** [comment]
I'm googling how/where to configure GH pages and not finding anything. Pls give me a pointer. :)

**Comment by carlisia** [comment]
Found.

**Comment by carlisia** [comment]
This is the updated setting:

![image](https://user-images.githubusercontent.com/16508/71101897-54bbcd80-216c-11ea-95bf-27ebdab495cb.png)

**Comment by carlisia** [comment]
@cpanato pls confirm that the source for the GH Pages should be the `gh-pages` branch and not `master`.

**Comment by nrb** [comment]
Looks correct to me. Resolves to https://vmware-tanzu.github.io/helm-charts/ at the moment.

**Comment by carlisia** [comment]
Yep!
![image](https://user-images.githubusercontent.com/16508/71112062-930eb800-217f-11ea-94ba-3b39d69f2e21.png)

Closing this issue as it is done.

**Comment by cpanato** [comment]
@carlisia yes the github page should point to `gh-pages` branch :)
