### ISSUE TITLE
Release 2.9.9 breaks volumesnapshotlocation.yaml

### ISSUE THREAD

**Issue by limed** [vmware-tanzu/helm-charts#93]
It appears the the last release and the commit e38dce798a43f0cf5400b0da5f0699798ab3182f broke the helm chart and I can now not install this chart (it was working previously)

It throws the following error:

```bash
$  helm template  --set configuration.provider=aws \
--set configuration.volumeSnapshotLocation.name=aws \
--set configuration.volumeSnapshotLocation.config.region=us-west-2  .
Error: YAML parse error on velero/templates/backupstoragelocation.yaml: error converting YAML to JSON: yaml: line 7: block sequence entries are not allowed in this context
```

**Comment by carlisia** [comment]
Hm. I guess I failed to test that PR. With either that commit or the branch for the PR https://github.com/vmware-tanzu/helm-charts/pull/94 I get the error below:

```
helm3 install /Users/carlisia/work/src/github.com/vmware-tanzu/helm-charts/charts/velero --namespace velero \ 
  --set-file credentials.secretContents.cloud=/Users/carlisia/creds/credentials-velero-minio \
  --set configuration.provider=aws \
  --set configuration.backupStorageLocation.name=aws \
  --set configuration.backupStorageLocation.bucket=velero \
  --set configuration.backupStorageLocation.config.region=minio \
  --set configuration.backupStorageLocation.config.s3ForcePathStyle=true \
  --set configuration.backupStorageLocation.config.s3Url=http://minio.velero.svc:9000 \
  ...
```

>Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(BackupStorageLocation): unknown field "s3ForcePathStyle" in io.velero.v1.BackupStorageLocation, ValidationError(BackupStorageLocation): unknown field "s3Url" in io.velero.v1.BackupStorageLocation]

If I revert the `backupstoragelocations` template to before the https://github.com/vmware-tanzu/helm-charts/commit/e38dce798a43f0cf5400b0da5f0699798ab3182f commit, it works.

The `s3ForcePathStyle` and `s3Url` fields are not part of the `backupstoragelocation`, but of the `aws` plugin. I'm not sure how we would set that up unless reverting to the way it was before, at least for these fields.

I didn't get the error reported here, maybe it just didn't make it that far.

**Comment by carlisia** [comment]
c/c @nrb and @cpanato.

**Comment by yurinnick** [comment]
I made a mistake in #82 in both backup and snapshots configuration formating. #94 supposer to fix snapshot part, while #96 will cover the rest, also adding the testcase into CI config.

**Comment by limed** [comment]
Hm so here is the error I'm actually getting running against the tip of master is this:

```bash
 helm template --set configuration.provider=aws --set configuration.backupStorageLocation.name=aws --set configuration.backupStorageLocation.bucket=foo --set configuration.backupStorageLocation.config.region=us-west-2 --set configuration.volumeSnapshotLocation.name=aws --set configuration.volumeSnapshotLocation.config.region=us-west-2 --skip-crds .
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
manifest_sorter.go:192: info: skipping unknown hook: "crd-install"
Error: YAML parse error on velero/templates/volumesnapshotlocation.yaml: error converting YAML to JSON: yaml: line 14: could not find expected ':'
```

Not sure why my first comment had an issue with `backupstoragelocation.yaml` but my issue is related `volumesnapshotlocation.yaml` and I can actually reproduce the  error each time running with the options in the code snippet.  Hopefully that helps.

Additional data point

```bash
$ helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Comment by yurinnick** [comment]
If you don't mind, please add additional changes from #96 to #94 so it will save some time on review.

**Comment by limed** [comment]
> If you don't mind, please add additional changes from #96 to #94 so it will save some time on review.

Took you changes and merged it into #94 in 45c2868563108bddc7aab7cd8f5369bdf6e8f90c

**Comment by carlisia** [comment]
Hey @limed and @yurinnick, great team work! I appreciate it.

Almost there. The issue now is that that block expects everything to be a string, but at least this one value is a boolean:

![image](https://user-images.githubusercontent.com/16508/78994383-c392ad00-7af4-11ea-9838-aaf34769a069.png)

**Comment by limed** [comment]
> Hey @limed and @yurinnick, great team work! I appreciate it.
> 
> Almost there. The issue now is that that block expects everything to be a string, but at least this one value is a boolean:
> 
> ![image](https://user-images.githubusercontent.com/16508/78994383-c392ad00-7af4-11ea-9838-aaf34769a069.png)

Apologies for the late reply, but I pushed a change in 8e98dd535052cba83ac2e3df3d87a19b63caae58 to hopefully fix this. I took what was available before the template would not render and incorporated it in to the PR
